### ISSUE TITLE
OpenGL2: r_ext_framebuffer_multisample draws flares through mirrors.

### ISSUE THREAD

**Issue by ghost** [ioquake/ioq3#121]
When flares are enabled (r_flares 1), and r_ext_framebuffer_multisample is > 1 than flares are seen through mirrors.

How to reproduce:
1. Start q3tourney6
2. set r_flares 1, r_ext_framebuffer_multisample 2.
3. Go to the BFG platform.
4. Have a look at the mirror floor at this platform.
5. You can see the flares from the main platform shining through the mirror floor.

Screenshot from q3tourney6:
![shot0003](https://cloud.githubusercontent.com/assets/5429387/7444932/3935cc64-f19c-11e4-98ac-dd0ca7f81140.jpg)

**Comment by ec-** [comment]
that's because glReadPixels doesn't work on multisampled FBO, you need to downsample it to regular FBO first, then depth tests will start working again
