### ISSUE TITLE
OpenGL2: vertexes deforming is not working.

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ioquake/ioq3#122]
Deforming vertexes (on models?) seems to no longer work. I'm not sure if this is the same issue: http://community.ioquake.org/t/deformvertexes-autosprite-issue-with-opengl2/472
At least CTF flags do no longer deform correct, the texture is flat. On map textures (banners on walls) the deforming is correct.
Screenshot from q3ctf4:
![shot0002](https://cloud.githubusercontent.com/assets/5429387/7444933/55a0540a-f19c-11e4-9578-29f54b29a530.jpg)

**Comment by ensiform** [comment]
This is long since known because he hasn't implemented it.

Good to have an issue of it to keep track of though.

**Comment by SmileTheory** [comment]
This should be fixed in https://github.com/ioquake/ioq3/commit/ad819edcc488f766acbabb57844fff1c5aa8f2ea .
