### ISSUE TITLE
Makefile can't find SDL2 in its local include directory (linux)

### ISSUE THREAD

**Issue by marko-lazic** [ioquake/ioq3#123]
Hi. Today i tried and failed to build this engine first time. My guessing is that it has something to do with Makefile which i am not expert of.

![bag](https://cloud.githubusercontent.com/assets/3621566/7901057/bd55c324-0776-11e5-868d-886b691dd400.png)

**Comment by ensiform** [comment]
I don't think it looks there by default on *nix

**Comment by zturtleman** [comment]
The local SDL2 header files are only used on Windows and OS X, which have pre-compiled SDL libraries in the repo. Even if they were used on Linux, SDL2 development files would still be needed for to finish compiling (linking) the client binary.

On Debian/Ubuntu you can install the SDL2 packages using

    sudo apt-get install libsdl2-2.0-0 libsdl2-dev

**Comment by TimeDoctor** [comment]
Closing, please ask on http://community.ioquake.org/ if you still have issues.
