### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by kallisti5** [ioquake/ioq3#127]
Could ioq3 tag a source release so packages can be built? I don't see a release of sources on the ioquake3 website... just binaries.

**Comment by TimeDoctor** [comment]
I'm the reason why we haven't had a release for a while. Here's [a thread on our forums] (http://community.ioquake.org/t/need-a-new-project-for-ioquake/487/5?u=timedoctor) with my reasoning, please reply there if you have any questions or further comments on the subject.
