### ISSUE TITLE
Unicode or Multi-Byte Character set for MSVC12 (VS2013) solution

### ISSUE THREAD

**Issue by shearer12345** [ioquake/ioq3#148]
I'm creating a Visual Studio solution (msvc12), but usage of non-UNICODE options has been deprecated - gives error
```Visual Studio error MSB8031: Building an MFC project for a non-Unicode character set is deprecated. You must change the project property to Unicode or download an additional library. See http://go.microsoft.com/fwlink/p/?LinkId=286820 for more information.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets	376	5	quake3```

Available solutions are:  (from, e.g. http://stackoverflow.com/questions/21360411/visual-studio-unable-to-recognise-my-mfc-library-for-my-webcam-laser-rangefinder)
1) change all projects to use Unicode
2) change all projects to use Multi-Byte Character set
3) install MFC MBCS DLL Add-on (https://msdn.microsoft.com/library/dn251007.aspx)

I would tend to go with 1), but presently the "q3_ui" and "ui" projects are set to use MBCS.

**Comment by timangus** [comment]
Do whatever the mingw build does.

**Comment by shearer12345** [comment]
Thanks.

After a bit of checking - it was a result of VS2013 defaulting to using MFC when not set. Not using MFC makes this irrelevant.

Cheers

Closing.
