### ISSUE TITLE
"pak0.pk3" is missing

### ISSUE THREAD

**Issue by nickdesaulniers** [ioquake/ioq3#151]
```
➜  ioq3 git:(master) ./make-macosx.sh x86_64
➜  ioq3 git:(master) ./build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/ioquake3
ioq3 1.36_GIT_f4aa39a-2015-08-25 macosx-x86_64 Aug 28 2015
Have SSE support
----- FS_Startup -----
Current search path:
/Users/Nicholas/Library/Application Support/Quake3/baseq3
./build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/baseq3
./build/release-darwin-x86_64/baseq3

----------------------
0 files in pk3 files
"pak0.pk3" is missing. Please copy it from your legitimate Q3 CDROM. Point Release files are missing. Please re-install the 1.32 point release. Also check that your ioq3 executable is in the correct place and that every file in the "baseq3" directory is present and readable
```

Where am I supposed to put the pak0.pk3 file? Maybe this error message could be updated?

**Comment by Koneke** [comment]
In either of
`/Users/Nicholas/Library/Application Support/Quake3/baseq3`
`./build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/baseq3`
`./build/release-darwin-x86_64/baseq3`

Not sure which one is the more convenient on Mac, but the structure on Windows is an ioquake folder, with the ioquake3 program itself in it, and a baseq3 folder with pk3s.

**Comment by TimeDoctor** [comment]
This is not a bug, we have a dmg file that users use to get things set up with the right directory structure and the error message specifies exactly where the baseq3 file should be:

/Users/Nicholas/Library/Application Support/Quake3/baseq3
./build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/baseq3
./build/release-darwin-x86_64/baseq3

**Comment by nickdesaulniers** [comment]
ah ok, cool thanks!

**Comment by nickdesaulniers** [comment]
huh, still running into trouble:
```
➜  ioq3 git:(master) ./build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/ioquake3
ioq3 1.36_GIT_f4aa39a-2015-08-25 macosx-x86_64 Aug 28 2015
Have SSE support
----- FS_Startup -----
Current search path:
/Users/Nicholas/Library/Application Support/Quake3/baseq3
./build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/baseq3
./build/release-darwin-x86_64/baseq3
./build/release-darwin-x86_64/baseq3/pak0.pk3 (3539 files)

----------------------
3539 files in pk3 files
Point Release files are missing. Please re-install the 1.32 point release. Also check that your ioq3 executable is in the correct place and that every file in the "baseq3" directory is present and readable
```

**Comment by TimeDoctor** [comment]
Please visit the help page on ioquake3.org it answers exactly that issue and continue this on community.ioquake.org.

**Comment by megamindbrian** [comment]
```xattr -d com.apple.quarantine /Applications/ioquake3/ioquake3.app```
