### ISSUE TITLE
ioquake3 crashes trying to download a pk3 file

### ISSUE THREAD

**Issue by redflo** [ioquake/ioq3#154]
Version from today, while trying to download, ioquake3 crashes. Stacktrace:

87074 times this line:
#87075 0x0000000000467367 in qcurl_easy_setopt_warn (curl=<optimized out>, option=<optimized out>) at code/client/cl_curl.c:235
#87076 0x0000000000467367 in qcurl_easy_setopt_warn (curl=<optimized out>, option=<optimized out>) at code/client/cl_curl.c:235
#87077 0x0000000000467367 in qcurl_easy_setopt_warn (curl=<optimized out>, option=option@entry=CURLOPT_URL) at code/client/cl_curl.c:235
#87078 0x00000000004674af in CL_cURL_BeginDownload (localName=localName@entry=0xec29d0 <clc+148912> "excessiveplus/z-xp-2_3.pk3", 
    remoteURL=0xd778a0 <string+32000> "http://xyz.com/somedir/excessiveplus/z-xp-2_3.pk3") at code/client/cl_curl.c:286
#87079 0x000000000041f577 in CL_NextDownload () at code/client/cl_main.c:2216
#87080 0x000000000041f6b2 in CL_InitDownloads () at code/client/cl_main.c:2286
#87081 0x0000000000424b31 in CL_ParseGamestate (msg=msg@entry=0x7ffd8e4308b0) at code/client/cl_parse.c:548
#87082 0x0000000000425018 in CL_ParseServerMessage (msg=msg@entry=0x7ffd8e4308b0) at code/client/cl_parse.c:919
---Type <return> to continue, or q <return> to quit---
#87083 0x0000000000422b2f in CL_PacketEvent (from=..., msg=msg@entry=0x7ffd8e4308b0) at code/client/cl_main.c:2809
#87084 0x0000000000456a4c in NET_Event (fdr=fdr@entry=0x7ffd8e4349d0) at code/qcommon/net_ip.c:1641
#87085 0x0000000000456e33 in NET_Sleep (msec=<optimized out>) at code/qcommon/net_ip.c:1698
#87086 0x000000000043c273 in Com_Frame () at code/qcommon/common.c:3127
#87087 0x0000000000405012 in main (argc=<optimized out>, argv=<optimized out>) at code/sys/sys_main.c:686

**Comment by TimeDoctor** [comment]
What operating system were you on?

**Comment by redflo** [comment]
opensuse 13.2 64 bit

**Comment by ensiform** [comment]
Latest code?

**Comment by redflo** [comment]
yes, pulled yesterday

**Comment by timangus** [comment]
Try the latest revision.

**Comment by redflo** [comment]
Impressive!

Works like a charm now. Thank you!

**Comment by timangus** [comment]
Would it be possible for you to try the latest revision too, and let us know if it still works? This one https://github.com/ioquake/ioq3/commit/9732f1ba69970c41e942b3234d6f510bf8622b06

**Comment by redflo** [comment]
Hi, latest version works too.
