### ISSUE TITLE
OpenGL2:  DM11 and DM12 fail to load (HUNK_ALLOC failed)

### ISSUE THREAD

**Issue by weirddan455** [ioquake/ioq3#156]
DM11 and DM12 both fail to load when playing through the single player campaign mode using the OpenGL2 renderer (works fine with OpenGL1.)  The error for DM11 is "HUNK_ALLOC FAILED ON 249696" and for DM12 "HUNK_ALLOC FAILED ON 3594624."

DM12 will load fine if you use skirmish mode regardless of number of bots (only fails from campaign mode) and DM11 will load from skirmish mode IF you use 3 of less bots (any more and it fails and the error number varies depending on how many bots.)

I am using the pak0.pk3 from my retail Quake 3 CD.  There may be other maps that fail as well.  I haven't tested all of them.

EDIT:  I'm using the latest git build, compiled today (g1902b6e.)  I was originally using a build from April (04-12-2015, g10c5f0b) and it was broken there too.  Also I'm using Arch Linux.

**Comment by ensiform** [comment]
What com_hunkmegs are you using?  Did you consider upping it?  Modern renderer will of course use more memory.

**Comment by weirddan455** [comment]
Thanks, I didn't know about that setting.  I was using the default of 96.  I bumped it up to 256 and now those maps work.  Is 256 a good number or should I do more?  I have 16GB of RAM so that's not an issue.

**Comment by weirddan455** [comment]
Actually nevermind, that didn't fix it.  I forgot to set my renderer back to opengl2.  I bumped my com_hunkMegs all the way to 2048 and I'm still getting the same error.

**Comment by weirddan455** [comment]
Wow OK sorry in advance for the comment spam.  It DID work.  I didn't realize I had com_hunkmegs set in my autoexec.cfg so my previous attempts to change it got undone on restart.

Set com_hunkmegs to 256 (which I'm hoping is a good setting) and those maps now work on opengl2.
