### ISSUE TITLE
Why is r_forceSun only possible with cheats enabled?

### ISSUE THREAD

**Issue by ScyDev** [ioquake/ioq3#158]

**Comment by Razish** [comment]
In competitive games, real-time projected shadows is often considered cheating as you may be able to see people around corners due to wonky/extreme shadows.
I suspect it was made a cheat because ioq3 is used for multiple games.

**Comment by ScyDev** [comment]
Would it be possible to make this a startup parameter for ioq3 or a server config, separate from cheats?
I would really love to be able to play with sun (and other new graphic features) without enabling all cheats commands.

**Comment by ensiform** [comment]
I don't see a reason for that.  The r_forceSun command is only useful for seeing a faked version of sun on old maps.  Its not really meant as a replacement for new maps with proper sun support.

**Comment by ScyDev** [comment]
The reason would be that people like to play the old maps.

**Comment by ensiform** [comment]
Right, and r_forceSun is a cheat to TEST the feature on old maps not to play live servers with it.
