### ISSUE TITLE
Client Shutdown (Client fatal crashed: GLimp_Init() - could not load OpenGL subsystem)

### ISSUE THREAD

**Issue by source83** [ioquake/ioq3#160]
I'm on Ubuntu 15.10 with Gallium 0.4 open source amd driver from git.
OpenGL applications DO run, but I don't know what's causing this problem.
Tell me what info you need and you'll have it :)

**Comment by ensiform** [comment]
Start with +set logfile 2 and give the qconsole.log file contents.  It'll be in the homepath for q3.

**Comment by TimeDoctor** [comment]
Please upgrade to a test build http://ioquake3.org/get-it/test-builds/ and if you need further support visit our forums http://community.ioquake.org/

**Comment by source83** [comment]
same result on the test build.
Also, using "+set logfile 2" didn't produce qconsole.log.

**Comment by Razish** [comment]
It would have produced the logfile in `fs_homepath`. If not, just run ioq3 inside a terminal.

**Comment by TimeDoctor** [comment]
Unfortunately this is not a support forum, please post in the forums with your issue.
