### ISSUE TITLE
lighting issue on a custom map

### ISSUE THREAD

**Issue by porto881** [ioquake/ioq3#163]
Hello, 
I recently downloaded the map Grindill 2.0 (http://lvlworld.com/comments/id:1691) but when I play it using the ioquake3 engine the lighting is terrible (http://imgur.com/a/p0BQB). I don't have this problem when I play the map using the original quake3 engine. I'm using windows 10. People playing on linux say it's working fine for them. Also, I have a GTX970 graphics card, if that makes any difference.
I hope you'll be able to fix this issue because it really is a cool map
Thanks in advance!

David

**Comment by TimeDoctor** [comment]
Please upgrade to a test build http://ioquake3.org/get-it/test-builds/ and post your issue on the community forums if it continues: http://community.ioquake.org
