### ISSUE TITLE
ioquake3 is lacking releases

### ISSUE THREAD

**Issue by jwrdegoede** [ioquake/ioq3#164]
Hi,

Fedora ioquake3 package maintainer here. I think that it is great to see that ioquake3 is still seeing active development. But as a Linux distro packager I would really like to see you do releases, or at a minimum do git tags at points in time when you consider the code to be fully stable / tested. E.g. when you build new binaries for your download page.

For example it would be good to know from which git commit the official 1.36.7.1 Linux binaries are builds. Using git tags for this will also make your own live easier when you get bug-reports for the official binaries.

Thanks & Regards,

Hans

**Comment by TimeDoctor** [comment]
Thanks for your input. I would really like to do a release, here's why we aren't going to do one right now:
http://community.ioquake.org/t/need-a-new-project-for-ioquake/487/5
