### ISSUE TITLE
RoQ2 tools ?

### ISSUE THREAD

**Issue by motorsep** [ioquake/ioq3#168]
Does ioq3 support RoQ/RoQ2 ?

If so, is there a code, compileable with MSVC2013 CE / MSVC2015 CE / gcc (linux) available? (hopefully configurable with cmake)

Thank you.

**Comment by ensiform** [comment]
Were the tools on the idsoft q3 release of q3 with source or only binary form with sdk?

**Comment by raynorpat** [comment]
cl_cin.c for playback
https://github.com/TTimo/GtkRadiant/blob/master/tools/quake3/q3data/video.c for actual roq compilation

**Comment by motorsep** [comment]
Aha, I see it: https://github.com/ioquake/jedi-outcast/tree/master/utils/roq2

Except there is no solution there for MSVC :/

**Comment by ensiform** [comment]
Nope because it was never built for windows.

**Comment by motorsep** [comment]
Is it hard to add cmake to configure builds for MSVC and gcc ?

**Comment by ensiform** [comment]
The dsw file is there so it was apparently for VC6.

**Comment by TimeDoctor** [comment]
I don't think that this is an issue for ioquake3.
