### ISSUE TITLE
cmakelist.txt missing

### ISSUE THREAD

**Issue by chasetheswift** [ioquake/ioq3#171]
Trying to build on Windows with Eclipse cdt. Cmake is giving me an error on cmakelist.txt missing. Is there one lying around or do I have to write my own (learn how to).

**Comment by ensiform** [comment]
This project doesn't support CMake so why would you make an issue about it missing?

Ideally it would be a nice option, but you'll have to create your own for the time being based off of the makefile and then add windows features to it.
