### ISSUE TITLE
JSON Build Failure in Linux

### ISSUE THREAD

**Issue by Danfun64** [ioquake/ioq3#176]
For whatever reason, I get the error "code/renderergl2/tr_bsp.c:27:29: fatal error: ..\qcommon\json.h: No such file or directory
compilation terminated." when I attempt to compile ioquake3.

Either there is an obvious solution that I am overlooking, or something needs to be fixed.

**Comment by Danfun64** [comment]
Still get the same error in the same place.

**Comment by ensiform** [comment]
It hasn't been fixed yet so, yeah.

**Comment by TimeDoctor** [comment]
This issue should be resolved, please recompile.

**Comment by robo9k** [comment]
Fixed in 0f6f2be155ad2750498ed69c0018602fb5282f63, compiles again on Linux.
