### ISSUE TITLE
r_overbrightbits behavior GL1 vs GL2

### ISSUE THREAD

**Issue by wareya** [ioquake/ioq3#178]
In GL1, r_overbrightbits does not affect the brightness of fullbright objects (armor, parts of ammo pickups, quad damage, etc). In GL2, it does. r_overbrightbits is 1 by default, so this makes armor and everything twice as bright in GL2.

If r_overbrightbits will affect the brightness of this kind of object in GL2, there should at least be a 1 bit penalty to this kind of object so that it looks the same as GL1 on default settings.

It looks like armor, quad, and the fullbright part of health pickups get bitshifted twice, while health does not.

**Comment by ensiform** [comment]
gamma and overbrightbits is accelerated in GL2 as a glsl shader IIRC which could be the difference.

**Comment by wareya** [comment]
The banner models on q3dm6 and other maps also seem to be lit funny, but in the opposite direction. But I'm not sure.

**Comment by wareya** [comment]
This should illustrate the problem: http://screenshotcomparison.com/comparison/180537

In **vanilla quake 3**, with default settings, the opengl2 rendering backend makes various elements look darker or brighter than they should be. The way lighting information propagates through the renderer is different than it should be.

**Comment by SmileTheory** [comment]
I think this is (mostly) a misunderstanding.

GL1 overbrights differently depending on r_fullscreen.  GL2 does not, and acts as if r_fullscreen was always on.

Here are some screenshots to demonstrate:

![gl1full0](https://cloud.githubusercontent.com/assets/1424196/19269205/243026f4-8f6e-11e6-9f3d-b8735dee90b8.png)
OpenGL1 renderer, r_fullscreen 0

![gl1full1](https://cloud.githubusercontent.com/assets/1424196/19269207/24368242-8f6e-11e6-806a-65596a170ad9.png)
OpenGL1 renderer, r_fullscreen 1

![gl2](https://cloud.githubusercontent.com/assets/1424196/19269206/24346cfa-8f6e-11e6-9aef-283e0896e85f.png)
OpenGL2 renderer

These screenshots don't show the fog however, which is wrong regardless of overbright settings.  I don't have a good fix for that, though.

**Comment by wareya** [comment]
I can't replicate your fullscreen gl1 screenshot. gl1 looks like your windowed version at all times.

**Comment by SmileTheory** [comment]
Thing is, the "one way" as you put it, is the correct way.  With r_fullscreen 0, GL1 simply ignores the r_overbrightBits value, and acts as if it were set to zero.  If you want GL2 to behave like GL1 non-fullscreened, just set r_overbrightBits to zero.

**Comment by wareya** [comment]
Thanks for explaining. One more thing is the 3d player head model on the HUD is a different brightness between gl1 and gl2 on default settings (it's brighter on gl1), but that might be CPMA doing something weird.

**Comment by ensiform** [comment]
You should not compare cpma directly with the stock version IMO since the source is closed we don't know for sure there's differences in its source.

**Comment by wareya** [comment]
CPMA is a mod/game, not an engine thing. Unless it's trying to detect engine variants it shouldn't have weird shading stuff going on that vanilla wouldn't if it did the same stuff.

**Comment by ensiform** [comment]
I know what CPMA is, I was simply stating that since you implied "CPMA might be doing something weird..."

The lighting in rend2 isn't going to be 1:1 perfect with vanilla still which is something @SmileTheory will need to work on I'm sure.

**Comment by SmileTheory** [comment]
Anyway, I put in a fix for the fog color in https://github.com/ioquake/ioq3/commit/863adfcfc274b24472c97281afcb809c6212ff11 , and everything else is fixable via cvars, so I'm closing this.

**Comment by wareya** [comment]
Thanks!

**Comment by wareya** [comment]
Looking back on this, it seems like it's *not* possible to get HDR lightmaps without breaking entity lighting, by using cvars.
