### ISSUE TITLE
Issue with building on ubuntu-mate 16.04 powerpc

### ISSUE THREAD

**Issue by tlosm** [ioquake/ioq3#182]
i have libsdl2-dev 2.04 and libsdl2 2.04 on my system but dont build
LD build/release-linux-ppc64/ioquake3.ppc64
/usr/bin/ld: skipping incompatible /usr/local/lib/libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible /usr/local/lib/libSDL2.a when searching for -lSDL2
/usr/bin/ld: skipping incompatible //usr/lib/powerpc-linux-gnu/libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible //usr/lib/powerpc-linux-gnu/libSDL2.a when searching for -lSDL2
/usr/bin/ld: skipping incompatible //usr/local/lib/libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible //usr/local/lib/libSDL2.a when searching for -lSDL2
/usr/bin/ld: cannot find -lSDL2
collect2: error: ld returned 1 exit status
Makefile:2054: recipe for target 'build/release-linux-ppc64/ioquake3.ppc64' failed
make[2]: *** [build/release-linux-ppc64/ioquake3.ppc64] Error 1
make[2]: Leaving directory '/home/amigaone/src/ioq3'

**Comment by ensiform** [comment]
Seems like you don't have a compatible version for your architecture though.

**Comment by tlosm** [comment]
Hi ensiform, i dont know all build without problems with sdl2 here tested with: 
dhewm3 (doom3), qemu 2.5 --with-sdlabi=2.0 and so and so . 
ok i will try to come in irc .  I have a quad g5 too i can test it there too.
thanks for your reply 
Luigi

**Comment by tlosm** [comment]
confirmed same issue come on Ubuntu Mate 15,10 on quad  g5 it dont find right sdl config 
 build/release-linux-ppc64/ioquake3.ppc64
/usr/bin/ld: saltato /usr/lib/powerpc-linux-gnu/libSDL2.so incompatibile durante la ricerca di -lSDL2
/usr/bin/ld: saltato /usr/lib/powerpc-linux-gnu/libSDL2.a incompatibile durante la ricerca di -lSDL2
/usr/bin/ld: impossibile trovare -lSDL2
collect2: error: ld returned 1 exit status

**Comment by TimeDoctor** [comment]
This is an issue with your distro version of SDL 2 or something, not a bug with ioquake3.
