### ISSUE TITLE
Issue with building on Debian Jessie powerpc

### ISSUE THREAD

**Issue by tlosm** [ioquake/ioq3#183]
I dont know why doctor close the discussion about ... in any way i tested ioq3 on Debian Jessie .... with the same result of mate 

D build/release-linux-ppc64/ioquake3.ppc64
/usr/bin/ld: impossibile trovare -lSDL2
collect2: error: ld returned 1 exit status
Makefile:2054: set di istruzioni per l'obiettivo "build/release-linux-ppc64/ioquake3.ppc64" non riuscito
make[2]: *** [build/release-linux-ppc64/ioquake3.ppc64] Errore 1
--- just for be sure 

/src/ioq3# aptitude search libsdl2-dev
i   libsdl2-dev

**Comment by ensiform** [comment]
It means your distributions do not have the proper SDL2 for your architecture or at least not in the correct location once again.  Build it from source as well and you might have better luck.

**Comment by tlosm** [comment]
Hi ensiform.
i did it  too build the sdl from sources but i face the same error

**Comment by TimeDoctor** [comment]
The previous issue was closed because it was not an issue with ioquake3. Please feel free to discuss the issue further on the forums and IRC or directly email me if you have questions about why that and this thread are closed. zachary@ioquake.org
