### ISSUE TITLE
Where is bspc?

### ISSUE THREAD

**Issue by tkoeppe** [ioquake/ioq3#202]
The upstream source release of the idtech3 engine contains the `bscp` command-line tool in `code/bspc`. Why isn't it also part of ioq3? The closest I could find is this repository: https://github.com/bnoordhuis/bspc

But it has a lot of overlap with ioq3, requiring code duplication and hackery, and it doesn't seem to have been updated in two years. Would it be possible to integrate that repository into this one? After all, all the code comes from the same source and is under the same license.

**Comment by ensiform** [comment]
ioq3 doesn't contain tools afaik.  You can find the real ones with TTimo/GtkRadiant and TTimo/bspc

**Comment by tkoeppe** [comment]
Ah, very good - and TTimo/bspc is itself a continuation of the repository I mentioned. Thanks!
