### ISSUE TITLE
Inputs are given maximally delayed timestamps in sdl/sdl_input.c: IN_ProcessEvents

### ISSUE THREAD

**Issue by wareya** [ioquake/ioq3#215]
Com_QueueEvent uses the "current time" in the way that the sdl driver is using it. Inputs are polled right before running the framerate limiter*. This means that for inputs supporting subframe timings, like the exact start time of pressing strafe keys on the ground, have unnecessary input lag. Quake 3's original input codepath propagates input timestamp information here, but SDL's input system does _not_ support accurate input timestamps.**

Quake 3's delta time paradigm "ends" a tick on the "current time" that it starts being simulated at. If a valid input event timestamp cannot be gotten from the input driver, then input events must be timestamped with the time that the tick "begins" on, which works out to the real time at the moment the _former_ tick began being simulated.

\* Which is the wrong thing to do, but the timestamp problem becomes the limiting factor if inputs are polled after the framerate limiter or if performance is bad.

*\* Yes, SDL events have a timestamp field. No, that information is not valid for input events, it gives the time that the input queue started being cycled.

**Comment by ensiform** [comment]
See: https://github.com/JACoders/OpenJK/commit/ba25e504f2f9c879e91268795919f35182553d3b

**Comment by wareya** [comment]
That's a second issue. This issue means that timestamp-aware input events (like starting ground movement) aren't unlagged when you fix the framelimiter issue alone. Both have to be fixed for timestamp-aware inputs to be unlagged.

**Comment by shoober420** [comment]
I hope this gets merged into the master branch of ioquake3.

**Comment by smcv** [comment]
@wareya: do you have a specific change that you are recommending? I think it would be most likely to happen if you send a pull request.

(I am not an ioquake3 maintainer and cannot accept pull requests myself.)

**Comment by wareya** [comment]
There are several ways to correct the problem, and I don't know the ropes of quake 3's engine well enough to decide which is best myself.

**Comment by zturtleman** [comment]
Committed a fix in https://github.com/ioquake/ioq3/commit/63e07afae922050d9b9fec1600044d9e07f088be. Thanks @wareya.
