### ISSUE TITLE
HTTPS issue on ioquake3.org

### ISSUE THREAD

**Issue by rcgordon** [ioquake/ioq3#217]
ioquake3 serves correctly over https, but the main page serves the background image with a non-SSL URL:

    http://www.ioquake3.org/bg/4.jpg

(this might actually be a PHP thing, because a reload got me 3.jpg instead of 4.jpg)

This causes Chrome to declare the page "insecure". This should either be "https://www.ioquake3.org/bg/4.jpg" or better yet just "/bg/4.jpg".

This is in this piece of the page...

<style>body{background-image:url('http://www.ioquake3.org/bg/3.jpg');}</style>

...right below the Twitter card floof.

--ryan.

**Comment by TimeDoctor** [comment]
Should be double checked. Fixed the code on my phone though so I can't test the fix. Please re-open if it isn't fixed.

**Comment by rcgordon** [comment]
Definitely works now, thanks!
