### ISSUE TITLE
Mouse click (fire) only happens in 90% of clicks!

### ISSUE THREAD

**Issue by exebook** [ioquake/ioq3#238]
In game it feels like my weapon is not reliable) If I fire a railgun or a rocket launcher, only 9 out of ten clicks produce the actual shot.

In menus this is even worse, any button I want to click, the chance that nothing will happen is very high! I found that if I click the "START" button for example, and nothing happens, I can click in vain for as long as you want, nothing will happen until I move the mouse pointer a little. 

It feels there are "blind spots" on the screen where mouse buttons do not work.

I tried to use another physical mouse, wired and wireless, the same behavior is still there.

I installed ioquake from Ubuntu repository. `apt-get install ioquake`.

`ioq3 1.36+u20150710+dfsg1-1/Ubuntu linux-x86_64 Jul 12 2015`

**Comment by ensiform** [comment]
Try a test build from here:

http://ioquake3.org/get-it/test-builds/

Should be able to just extract and replace the files from the archive to where you installed to and overwrite.

**Comment by exebook** [comment]
Seem to have helped.
