### ISSUE TITLE
AutoDownload Hangs at 32mb

### ISSUE THREAD

**Issue by haxxus** [ioquake/ioq3#240]
Server running the 11/25/16 git version , and is been like this for previous versions too , basically download hangs at 32mb for any pk3 higher than 32mb and you see the download speed starts to lower down to 0 slowly . Now I'm using regular q3a to connect to the server I'm not sure that matters .

**Comment by ensiform** [comment]
You need ioquake3 client to have the larger UDP download sizes.  Pretty sure this was a fix in the client specifically.  You can of course use HTTP/FTP download redirect as well if supported by the server you connect to for potentially even faster speeds.

**Comment by haxxus** [comment]
I use http redirect , not sure if it kicks in with regular q3a client  , but speed seems to stay around 250 kb's if I use http dlurl or not, so it might not be working for q3a client.
So question, there is nothing at server side that can increase download size for q3a client? maybe a sv_ command or something.

**Comment by haxxus** [comment]
for example the sv_dlrate is not found on q3a , but does work with q3a client connecting to ioq3 server.

**Comment by haxxus** [comment]
Yes q3a client doesn't pick the url redirect , with ioq3 client download speed is 3.5 mb and no problems with pl3 size. 
Only problem I have now is major fps drop with ioq3 client , Using same .cfg on dm17 it drops anywhere from 30 to 250 , with regular q3a is solid 250

**Comment by haxxus** [comment]
The problem is with the git ioq3 version , tried both 64/32 bit compiled with Cygwin for Windows, using windows 10.
No problems with ioquake3-1.36-3.1.x86

**Comment by ensiform** [comment]
Q3A doesn't have URL redirect, this is a feature of ioquake3.  The download speed of a server running the original quake3 is tied to the user's rate setting (which is capped by sv_maxRate).  In ioquake3 there is that separate sv_dlRate to decouple that.  But the download sizes issue is limited in the client not on the server side.

**Comment by TimeDoctor** [comment]
This sounds like it isn't a bug with ioquake3, and you just need to use an ioquake3 client to get a larger download, so I'm closing this issue.
