### ISSUE TITLE
console date in version string is wrong

### ISSUE THREAD

**Issue by TimeDoctor** [ioquake/ioq3#243]
A test build downloaded today (december 5th) and a build I compiled today both display the date of 2016 5 15
![shot0003](https://cloud.githubusercontent.com/assets/903791/20910817/05361ebe-bb08-11e6-9287-23af21daa187.jpg)

**Comment by ensiform** [comment]
Even a clean full build from your system shows that?

**Comment by TimeDoctor** [comment]
I cleaned before building. I will try moving my quake 3 folder out of the way. Should mention this is macOS Sierra.

**Comment by TimeDoctor** [comment]
This turns out to not be a bug and is instead the result of the reproducible build commit. So even though the most recent commit was created before the previous commit, we get the date of the git commit and not the date of the build or when the code was merged. You'd think I would know better. That's kind of strange but I suppose this won't happen that often.
