### ISSUE TITLE
Generated normalmap is broken on some shaders

### ISSUE THREAD

**Issue by wtfbbqhax** [ioquake/ioq3#245]
# Problem description
### Screenshot

![image](https://cloud.githubusercontent.com/assets/7323455/21078632/2c7bd60e-bf44-11e6-9465-d0ab317b361d.png)

#### Configurations
```
cl_renderer opengl2
r_genNormalMaps 1
```

#### What I know

1. Occurs on Windows/Linux/OSX
2. Consistent, same shaders every time
3. These shaders did not have a "normal map", it was generated

* I've also noticed, that they are always shifted an additional (.5*width) to the right.

----

Curious if you've seen this, perhaps already fixed it? This has been a consistent problem we've seen.

**Comment by ensiform** [comment]
Mod? Up to date renderer?

**Comment by wtfbbqhax** [comment]
Our Tremulous fork is sync'd up to ioq3 c5c01e771a2eb01d5c6bc994fff272bf2469fb26

To prevent missing our target date for release, I will not be merging anytime soon. Until a solution to #214 we will only merge renderergl2 changes I think.

**Comment by SmileTheory** [comment]
Fixed in https://github.com/ioquake/ioq3/commit/294109628d87df8c151f956b4c6bbc3d2381ae39 .
