### ISSUE TITLE
OpenGL2 - DLights Show Textures with r_lightmap "1"

### ISSUE THREAD

**Issue by ZdrytchX** [ioquake/ioq3#246]
Screenshot taken from Tremulous with the prerelease 1.2 GL2 Client.
![pasted_image_at_2016_12_14_23_06](https://cloud.githubusercontent.com/assets/1125998/21187896/83b893ea-c254-11e6-9e9f-8865933781c3.png)

Replication:
r_lightmap "1"
fire your gun, note that textures will appear within the dynamic lighting area.

**Comment by ensiform** [comment]
At what code-point is this forked from ioquake3 though?  Chances are it might be fixed upstream or specific to changes in trem.

**Comment by wtfbbqhax** [comment]
@ensiform He's with me, Tremulous fork is synced up to ioq3 c5c01e7

**Comment by SmileTheory** [comment]
Since r_lightmap is for viewing lightmaps while making a map, I've fixed this by just disabling dlights while r_lightmap is on.
