### ISSUE TITLE
mingw-w64 builds use wrong vsnprintf

### ISSUE THREAD

**Issue by birdstakes** [ioquake/ioq3#250]
When building with mingw-w64, msvcrt.dll's broken _vsnprintf is used for Q_vsnprintf. There is already a version of Q_vsnprintf that is a wrapper for _vsnprintf (used if _MSC_VER is defined), or mingw-w64 has their own standards-compliant vsnprintf that can be used by defining __USE_MINGW_ANSI_STDIO.

**Comment by zturtleman** [comment]
Fixed in 83119a990a160e9c1e19dc06e04ae8f947a57904. Thanks.
