### ISSUE TITLE
Windows x86 dedicated server crashing on startup

### ISSUE THREAD

**Issue by Chomenor** [ioquake/ioq3#257]
As the title says. I'm having intermittent crashes starting the dedicated server from [http://ioquake3.org/files/jenkins/latest/gcc/no_options/release-mingw32-x86.zip](http://ioquake3.org/files/jenkins/latest/gcc/no_options/release-mingw32-x86.zip)

This is on Windows 10. The crash traces to `main->Com_Init->Com_Printf->Sys_Print->CON_Print->CON_Hide->CON_Show->WriteConsoleOutput`. From what it looks like WriteConsoleOutput is being passed the qconsole_hout handle that hasn't been initialized yet, because CON_Init hasn't been called yet.

Based on a quick test, moving CON_Init ahead of COM_Init in main seems to stop the crash, but I don't know if it would cause any other problems.

**Comment by TimeDoctor** [comment]
are you still having this crash?

**Comment by Chomenor** [comment]
Yes, in fact I recently encountered this crash in a 64-bit build as well. It is intermittent and doesn't happen on all systems all the time. The bad handle is probably causing indeterminate behavior in Windows that only sometimes leads to a crash.

**Comment by timangus** [comment]
Could you open a PR with your change?

**Comment by Chomenor** [comment]
I created the PR, but currently haven't tested it very much.

**Comment by timangus** [comment]
Thanks!
