### ISSUE TITLE
Model/skin loading fails (ignoring surfaces, , the max is 32 surfaces).

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ioquake/ioq3#261]
Current ioquake3 master can't load model skin (max. 32?). The specific model is called: q3mdl-q4hybrid.
You can either get it from ioquake3 extras/model site: https://ioquake3.org/extras/models/
or from here: https://ws.q3df.org/models/?model=q4&x=0&y=0

Trying to load the model will give this result:
1. There is a warning message in the console: **_WARNING: Ignoring surfaces in
'models/players/q4hybrid-low/lower_solair.skin', the max is 32 surfaces!
unknown token 'Fixedlegs' in models/players/q4hybrid-low/animation.cfg_**

2. The model will load into game but some parts (the head skin) is missing.

Both renderers are affected. The model loads without problems in vQ3A.
Thanks.

**Comment by ensiform** [comment]
I think this means the model has exactly 32 surfaces?  ioquake3 has protections to avoid crashes with too many surfaces in a model.

**Comment by KuehnhammerTobias** [comment]
Yeah, but I wonder why the bug also happens with Zturtleman's Spearmint/Mint-Arena. Don't get me wrong, but the model never crashed iirc, so why shouldn't it load all the skins that are needed?
Hmm, I just thought this is some new bug, though probably I'm wrong. I didn't talk to Zturtleman about that recently.
Well, I'm no expert, maybe I do not understand why preventing this model from loading makes sense.
Thanks for the reply/help!

**Comment by timangus** [comment]
It's possible that idq3 works because the memory that is being trampled on by breaching 32 surfaces is not used for anything else, or nothing that causes obvious problems or crashes. But that's just a guess really; I haven't looked at the code.

**Comment by ensiform** [comment]
I actually looked at tr_model and the only change I saw was regarding SHADER_MAX_VERTEXES not the number of surfaces.  Someone else can dig further. out for the day.

**Comment by zturtleman** [comment]
Fixed in https://github.com/ioquake/ioq3/commit/904bbc1a8fd83d6798c35975726440e4b8221d31.
