### ISSUE TITLE
(Linux) Com_WriteConfig_f: Only the ".cfg" extension is supported by this command!

### ISSUE THREAD

**Issue by moozhub** [ioquake/ioq3#280]
Whenever I try to "writeconfig", using the latest test build I'm receiving the message: 

"Com_WriteConfig_f: Only the ".cfg" extension is supported by this command!"

As far as I can tell it's not due to any type of permission issue as all subdirectories and files within the installation directory are owned by my user. Using the stable release within the Ubuntu repository didn't appear to pose this issue.

Here's a strace of the activity:

```
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(2, "]\\writeconfig autoexec\n", 23]\writeconfig autoexec
) = 23
write(1, "tty]", 4)                     = 4
mkdir("/home", 0750)                    = -1 EEXIST (File exists)
mkdir("/home/user", 0750)              = -1 EEXIST (File exists)
mkdir("/home/user/.q3a", 0750)         = -1 EEXIST (File exists)
mkdir("/home/user/.q3a/baseq3", 0750)  = -1 EEXIST (File exists)
stat("/home/user/.q3a/baseq3/q3history", {st_mode=S_IFREG|0664, st_size=647, ...}) = 0
open("/home/user/.q3a/baseq3/q3history", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 74
fstat(74, {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
write(74, "21 0 21 \\writeconfig autoexec 6 "..., 654) = 654
close(74)                               = 0
read(0, 0x7ffd04578fdf, 1)              = -1 EAGAIN (Resource temporarily unavailable)
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(1, "\10", 1)                      = 1
write(1, " ", 1)                        = 1
write(1, "\10", 1)                      = 1
write(2, "Com_WriteConfig_f: Only the \".cf"..., 75Com_WriteConfig_f: Only the ".cfg" extension is supported by this command!
) = 75
write(1, "tty]", 4)                     = 4
read(0, 0x7ffd04578fdf, 1)              = -1 EAGAIN (Resource temporarily unavailable)
```
Issuing the command with a ".cfg" extension returns the same result.

**Comment by SmileTheory** [comment]
Was this before or after https://github.com/ioquake/ioq3/commit/de3339ebcda1999b386534bc581b8fa7272a846e ? Because it's working for me.

**Comment by moozhub** [comment]
Not sure, I figured the test build on the main website might have been automatically built from master. If not I will pull master, build it and test it out a bit later.

**Comment by ensiform** [comment]
Sounds like you grabbed it from there from before that commit

**Comment by moozhub** [comment]
I downloaded the test build from the website last night to make sure of that, unless for some reason the mentioned commit wasn't included in that test build, then it's not repaired. Still can try and pull and build if that's what you're suggesting..

**Comment by moozhub** [comment]
This is still happening to me... running client version: `ioq3 1.36_GIT_25cc2ed-2017-03-23 linux-x86_64 Mar 23 2017`

I can't for the life of me understand why it's doing this...any help would be appreciated.

**Comment by TimeDoctor** [comment]
Good news
