### ISSUE TITLE
Mistyped dedicated server console commands are broadcast to clients

### ISSUE THREAD

**Issue by cdev-tux** [ioquake/ioq3#295]
If server commands are mistyped in the dedicated server console or through com_pipefile then the text is sent to clients as a server broadcast.  This is similar to the client issue fixed with [con_autochat](https://github.com/ioquake/ioq3/commit/dfce71929a1094526f6482eeb6a0cca11f4bc7a1).
Maybe something like sv_autochat could be implimented to allow default behavior.

**Comment by ensiform** [comment]
That was always default behavior.

**Comment by cdev-tux** [comment]
I knew that it was the default behavior, I was referring to creating a cvar to allow the user to set modified or default behavior.   Yeah, that's unfortunate that it can't be fixed across the board .

**Comment by ensiform** [comment]
Strangely the tty console supports con_autochat toggle but only in the dual-mode module and not in dedicated only mode. However, catch-me-all still happens in unregistered commands in g_svcmds.c here: https://github.com/ioquake/ioq3/blob/master/code/game/g_svcmds.c#L501-L509 like mentioned, which means it might not be worth it.
