### ISSUE TITLE
compiling ioquake3 from git on linux-ppc64 fails with libcurl array size errors

### ISSUE THREAD

**Issue by aperezbios** [ioquake/ioq3#298]
A fresh checkout of ioquake3 via git, and subsequent compilation on a debian sid (powerpc64) system today nets me:

make[2]: Entering directory '/home/aperez/ioq3'
LD build/release-linux-ppc64/ioq3ded.ppc64
CC code/client/cl_cgame.c
CC code/client/cl_cin.c
CC code/client/cl_console.c
In file included from code/client/../libcurl-7.35.0/curl/curl.h:35:0,
                 from code/client/cl_curl.h:31,
                 from code/client/client.h:34,
                 from code/client/cl_cgame.c:24:
code/client/../libcurl-7.35.0/curl/curlrules.h:142:3: error: size of array ‘__curl_rule_01__’ is negative
   __curl_rule_01__
   ^~~~~~~~~~~~~~~~
In file included from code/client/../libcurl-7.35.0/curl/curl.h:35:0,
                 from code/client/cl_curl.h:31,
                 from code/client/client.h:34,
                 from code/client/cl_cin.c:34:
code/client/../libcurl-7.35.0/curl/curlrules.h:142:3: error: size of array ‘__curl_rule_01__’ is negative
   __curl_rule_01__
   ^~~~~~~~~~~~~~~~
In file included from code/client/../libcurl-7.35.0/curl/curl.h:35:0,
                 from code/client/cl_curl.h:31,
                 from code/client/client.h:34,
                 from code/client/cl_console.c:24:
code/client/../libcurl-7.35.0/curl/curlrules.h:142:3: error: size of array ‘__curl_rule_01__’ is negative
   __curl_rule_01__
   ^~~~~~~~~~~~~~~~
Makefile:2624: recipe for target 'build/release-linux-ppc64/client/cl_console.o' failed
make[2]: *** [build/release-linux-ppc64/client/cl_console.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:2624: recipe for target 'build/release-linux-ppc64/client/cl_cgame.o' failed
make[2]: *** [build/release-linux-ppc64/client/cl_cgame.o] Error 1
Makefile:2624: recipe for target 'build/release-linux-ppc64/client/cl_cin.o' failed
make[2]: *** [build/release-linux-ppc64/client/cl_cin.o] Error 1
make[2]: Leaving directory '/home/aperez/ioq3'
Makefile:1325: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/home/aperez/ioq3'
Makefile:1276: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by zturtleman** [comment]
Fixed by #299.
