### ISSUE TITLE
sv_strictauth

### ISSUE THREAD

**Issue by haxxus** [ioquake/ioq3#302]
Hello, I'm having trouble using sv_strictauth, seems to not kick in from dedicated server start sequence or server.cfg, visually it does turn on from /rcon but doesn't function. 
Anyone has knowledge about it, maybe needs of another cmd or a file?

**Comment by zturtleman** [comment]
sv_strictauth value is sent to the Q3 authorize server. I think disabling it allows client to use different IP addresses when connecting to authorize server and game server.[[source]](http://zerowing.idsoftware.com/linux/q3a/) The Q3 authorize server is down so it doesn't have any affect.

**Comment by haxxus** [comment]
so there is no way to restrict duplicate cd keys / virtual fake ip's .

**Comment by ensiform** [comment]
There's no way to do this in any client including the original id software latest release. They shut the auth server down and it is not public.
