### ISSUE TITLE
OpenGL2: HDR/FB-MSAA + post process leaves out viewport trim (cg_viewsize < 100)

### ISSUE THREAD

**Issue by zturtleman** [ioquake/ioq3#304]
In the opengl2 renderer, the trim around the viewport when cg_viewsize is less than 100 is not visible when drawing to a frame buffer object (r_hdr 1 or r_ext_framebuffer_multisample > 0) and r_postProcess is 1.

It's drawn to the frame buffer object but it's not copied to the default framebuffer.

**Comment by kai-li-wop** [comment]
Is anyone here working on a solution for this? We recently discovered the same thing in WoP. https://github.com/PadWorld-Entertainment/worldofpadman/issues/154

**Comment by kai-li-wop** [comment]
@zturtleman: Are yo working on this issue? World of Padman would also benefit from a fix. Thank you.

**Comment by kai-li-wop** [comment]
Outstanding, thank you!

**Comment by zturtleman** [comment]
You're welcome.
