### ISSUE TITLE
systemd doesn't allow non-absolute executable paths in .service files

### ISSUE THREAD

**Issue by zeroxfourc** [ioquake/ioq3#306]
```
● q3a.service - This service spawns a ioquake3 dedicated server with sane defaults
   Loaded: error (Reason: Exec format error)
   Active: inactive (dead)

Sep 04 18:16:17 ingarill systemd[1]: /usr/lib/systemd/system/q3a.service:8: Executable path is not absolute: $(which q3ded) +set dedicated 2
```

I know this .service file differs slightly from yours as it's been patched by the `ioquake3-git` AUR package, but the error is in yours too.

**Comment by zturtleman** [comment]
Mm yeah, this issue was [reported back in 2014](https://github.com/ioquake/ioq3/pull/80#issuecomment-53951499) too. I've change it to the default absolute path for `make copyfiles` in ad10e6610c2f1064ac781936050f1d06ad8c67d1. Distro packages will need to change it. Thanks.
