### ISSUE TITLE
"/reconnect; password passwordhere" results in looping reconnects

### ISSUE THREAD

**Issue by Jon8RFC** [ioquake/ioq3#308]
With OSP, I was receiving the odd disconnect error each a map was reset after a match, or a map was switched.  I typed "/reconnect; password passwordhere" which resulted in the screen shrinking to what I think was 640x480 size, loading the map, going full screen, reconnecting and seemingly shrinking about 8 times, reloading the map, going full screen again, reconnecting, shrinking 8 times, repeat.

Windows 7 Pro x64
HD5870
ioq3 x64 2017-09-04 release

r_smp 1

**Comment by ensiform** [comment]
Was the password not set before ? It should still be retained.

**Comment by Jon8RFC** [comment]
I think I connected with "/connect ip;password pass" and when it
disconnected me, if I did just /reconnect, it said "invalid password" so
each time I'd do /password on each reconnect. I thought I'd save time by
making it one command but it caused the strange loop. It accepted the
password as valid because the map loaded, and I could open the console
briefly before it cycled, but the keyboard was dead so even a quick q-TAB
was not possible. Oddly, with the console open, I could hit ESC and the
menu popped up behind the console but nothing could be typed into the
console.

**Comment by ensiform** [comment]
Have you tried this issue if you load osp up directly before connecting to the server?

**Comment by Jon8RFC** [comment]
I'll give that a try the next chance I get, and let you know the outcome.

On Sep 9, 2017 17:08, "Ensiform" <notifications@github.com> wrote:

Have you tried this issue if you load osp up directly before connecting to
the server?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ioquake/ioq3/issues/308#issuecomment-328306273>, or mute
the thread

**Comment by Jon8RFC** [comment]
Wow, I'm embarrassed for having never responded.

I don't have this issue on ioq3 anymore, but I'm pretty sure the fix was loading osp before connecting, as suggested.  Thanks!

I added +set fs_game osp to my shortcut back then.  I just tested without that, and don't have looping reconnects anymore as of the compiled ioq3 a few days ago.
