### ISSUE TITLE
accuracy reward averages your previous performances when replaying the same map

### ISSUE THREAD

**Issue by illwieckz** [ioquake/ioq3#314]
Hi, I found that the accuracy reward average your previous performance if you replay the same map in a row.

## What is expected:

Accuracy being computed from shot count since the time the the game is restarted.

## What I get:

Accuracy being computed from shot count since since the time the map is loaded.

## How to reproduce:

**normal play**

- start _q3dm0_ map with _I can win_ difficult setting
- take shotgun
- jump into portal to enter arena
- hunt down Crash, do not miss any shot (not so hard :grinning: )
- note the 100% accuracy reward

**replay**

- leave the arena (return to menu)
- start _q3dm0_ map with _I can win_ difficult setting
- take shotgun
- deliberately shot 5 time in the air
- jump into portal
- hunt down Crash, do not miss any shot
- note the accuracy reward (something around 50%)
- hit "replay" button
- take shotgun
- jump into portal to enter arena
- hunt down Crash, do not miss any shot
- note the accuracy reward (something between 80 and 90%)

**Comment by illwieckz** [comment]
I also noticed the bot respawn behavior is not the same when loading a map and replaying a map, in the first case bot spawn when announcer announces its name (or something like that, in q3dm0 you can go to Crash spawn point and wait for her to spawnfrag her), in the later case, bot instantaneously spawn. It means it's harder to win a game when replaying a map (bot can pick-up weapons ans bonus earlier, or make points before you do). This one is more obvious and well-known I guess.

**Comment by zturtleman** [comment]
The player's accuracy resets each time but shotgun hits don't count as an accuracy hit if enemy had 10 health or less. If you shot Crash more than once to kill her it's possible the shot counted as an accuracy miss. Fixed in 51e9aa2df037e3df72bc5f3b663010b8f4986b14.
