### ISSUE TITLE
Missing shaders cause division by zero

### ISSUE THREAD

**Issue by DescX** [ioquake/ioq3#316]
Attached: Just a 3-liner diff. If you're super-duper-performance-conscious you may want to change it to an if/else, but there's no rocket science here to explain.

[tr_mesh.c_shaderIndexDivision.diff.txt](https://github.com/ioquake/ioq3/files/1357626/tr_mesh.c_shaderIndexDivision.diff.txt)

Have a good one.

**Comment by zturtleman** [comment]
Fixed in d824cfa5a2ced2cfbfbc89509b8415aefd30949b. Thanks.
