### ISSUE TITLE
OpenGL2: shaders, blendFunc, alpha channel

### ISSUE THREAD

**Issue by Tasijjj** [ioquake/ioq3#317]
![bush_problem](https://user-images.githubusercontent.com/32816558/31585614-f9e790b0-b1c4-11e7-9bbb-13081216e03f.png)

Hello,
is anybody familiar with the kind of "bug" shown on the picture?
Although, the smaller bush plant is clearly further away from the player than the bigger one, the texture of the distant bush plant has somehow priority over the texture of the closer one.

The shader code I'm using:

texturepath/texturename
{
	cull none
	{
		map texturepath/texturename.tga
		blendFunc blend
	}
}

Am I missing something in the shader?

Any kind of help would be appreciated.

**Comment by zturtleman** [comment]
Quake 3 doesn't preform distance sorting for blended surfaces. Consider replacing the `blendFunc` with an alpha mask (`alphaFunc GE128`) and `depthWrite`. Also see the discussion by Hipshot, sock, and obsidian for alpha masked grass with correct view order and a soft edge (`textures/moteof/grass01d_indoor`) [here](https://www.quake3world.com/forum/viewtopic.php?p=779616#p779616).

**Comment by Tasijjj** [comment]
Thank you for that clear and fast answer.

While waiting for the response, we found out, that UrbanTerror uses `alphaFunc 128` and `depthWrite` in its shaders for textures with alpha channel, so we used that as well.

Nevertheless, a confirmation, that something doesn't exist in the code, is always very helpful.
