### ISSUE TITLE
Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by aarodynamics** [ioquake/ioq3#318]
Windows Defender is reporting that there is a Trojan within .\missionpack\uix86_64.dll in the 2017-09-04 release. 

![2017-10-15 17_06_14-windows defender security center](https://user-images.githubusercontent.com/1323716/31590932-4104aa1a-b1ce-11e7-85be-d5040cb3d0ed.png)

**Comment by TimeDoctor** [comment]
I just scanned it on Windows 10 w/Windows Defender running the latest updates and didn't get any messages like that.

**Comment by wtfbbqhax** [comment]
Steam path?

**Comment by TimeDoctor** [comment]
I'm unable to reproduce this on my systems or through virustotal. Your system may have some malware that is injecting dlls, or this is a false positive. Please only download test builds through our website https://ioquake3.org/get-it/test-builds/

**Comment by TimeDoctor** [comment]
Would definitely reopen if someone can reproduce this.
