### ISSUE TITLE
Missing parts of brushes, GTK Radiant, BSP compiler

### ISSUE THREAD

**Issue by Tasijjj** [ioquake/ioq3#322]
Greetings.

Could someone explain the issue shown on the picture 1?

If it's not clear what's wrong, the picture 1 shows the compiled (in-game) part of terrain, made out of three sided brushes. There is clearly a part of brush missing. Could it be caused by the overlapping of brushes show on the pictures 2 and 3?

Shaders wise, I started with desired (brick) texture on every side of the brush. Then, I tried changing the sides, that are not "needed" for the terrain, to a texture, that would force the compiler not to write them in the .bsp file (is this even possible to achieve?).
I used `common/nodrawnonsolid` shader for this, because it seemed like it would do the job. Sadly, it didn't.

Brush shape wise, I tried making downward-facing pyramids (picture 4) instead of extruded triangles, so none of the brushes were overlapping and it didn't help.

![brez naslova](https://user-images.githubusercontent.com/32816558/32133383-087cd420-bbd7-11e7-971d-d60488ded125.png)

**Comment by zturtleman** [comment]
This issue tracker is for ioquake3 engine and game logic issues. Please ask Quake 3 modding questions on the [ioquake3 forum](http://discourse.ioquake.org/).
