### ISSUE TITLE
OpenGL2 lightmapping on multi-texture material on mpteam6 is wrong

### ISSUE THREAD

**Issue by wareya** [ioquake/ioq3#339]
GL2: 
![shot0019](https://user-images.githubusercontent.com/585488/35771853-636302de-0901-11e8-9e37-e1a6da31dfaa.jpg)

GL1:
![shot0017](https://user-images.githubusercontent.com/585488/35771835-06e293c6-0901-11e8-8059-e24f85c3404c.jpg)

The shadow is too dark. It looks like the lightmap is being applied twice or something.

This is some kind of multi-texture material.

GL1 r_lightmaps 1 (showing one of the textures):
![shot0020](https://user-images.githubusercontent.com/585488/35771844-27f84fe2-0901-11e8-98fe-e310fddc69a0.jpg)
GL1 r_lightmaps 0 (showing both textures):
![shot0021](https://user-images.githubusercontent.com/585488/35771845-2ce28efa-0901-11e8-88d0-0fe3e802278c.jpg)

(GL2 r_lightmaps 1 doesn't show the first texture, just the lightmap)

This patch appears to fix this instance of it but is almost certainly wrong:

    code/renderergl2/tr_shader.c
    @@ -2421,6 +2421,7 @@ static int CollapseStagesToGLSL(void)
     
        if (!skip)
        {
    +        int seen_lightmap = 0;
            for (i = 0; i < MAX_SHADER_STAGES; i++)
            {
                shaderStage_t *pStage = &stages[i];
    @@ -2477,9 +2478,10 @@ static int CollapseStagesToGLSL(void)
                            break;
     
                        case ST_COLORMAP:
    -						if (pStage2->bundle[0].tcGen == TCGEN_LIGHTMAP)
    +						if (pStage2->bundle[0].tcGen == TCGEN_LIGHTMAP && !seen_lightmap)
                            {
                                lightmap = pStage2;
    +							seen_lightmap = 1;
                            }
                            break;

**Comment by wareya** [comment]
This overlay on q3dm8 is broken by the patch I posted:

![shot0022](https://user-images.githubusercontent.com/585488/35773037-dcb31332-0914-11e8-9969-0a14a91e1a0a.jpg)

**Comment by zturtleman** [comment]
Yeah, the lightmap was applied multiple times. Fixed in 3d6aa05694cdfbfd630edb95f1096ed107b6a5d4. Thanks.
