### ISSUE TITLE
Is there any way to increase the 1024 in game entity cap?

### ISSUE THREAD

**Issue by KroniK907** [ioquake/ioq3#349]
Hello,

I have a map that I worked on that has a bunch of entities and it ends up hitting the limit of 1024 entities in a few places on the map. Strangely it runs the map just fine, but in a few locations, the game ends up loading more than 1024 entities. 

I'm not where to even start looking in the source code to see if this limit can be increased.

Is there any chance that this limit could be increased? 

Thanks

**Comment by zturtleman** [comment]
Closing issue, please use the [ioquake3 forum](http://discourse.ioquake.org) for general development questions.
