### ISSUE TITLE
How can I force depth_buffer_bit to 24

### ISSUE THREAD

**Issue by tangbohu** [ioquake/ioq3#354]
How can I force depth_buffer_bit to 24?

**Comment by zturtleman** [comment]
Open the console using ~ or shift+escape and type `\r_depthbits 24; vid_restart` and then press enter. (r_depthbits defaults to 0 which automatically uses depth bits 24.)

Use `\gfxinfo` to check how many depth bits are used (i.e., `PIXELFORMAT: .. Z(24-bit) ..`).

Please use the [ioquake3 forum](https://discourse.ioquake.org) for general questions.
