### ISSUE TITLE
+voiprecord does not work on Mac

### ISSUE THREAD

**Issue by pragmader** [ioquake/ioq3#357]
When I hold `+voiprecord` I see the volume meter at the top of the screen but it does not show any sound level like my input device is not connected. Other players on the server can't hear me either. I tried several options: a headset, external mic, built-in mic – none of them capture sound for ioquake3. Also, I have tried to reboot my Macbook and it has no effect.

ioquake3 acef71af5e1e79e4d72468492cffa054982c91e2 (built from sources, master branch)
Mac OS 10.13.3
MacBook Pro (Retina, 13-inch, Early 2015) 2,7 GHz Intel Core i5

My server and client have all default settings:

```
s_useOpenAL "1"
sv_voip "1"
cl_voip "1"
cl_voipUseVAD "0"
cl_voipGainDuringCapture "0.2"
cl_voipShowMeter "1"
cl_voipCaptureMult "2.0"
```

Is there any way to specify the input device manually in order to make it work? Or maybe there is another trick?

**Comment by zturtleman** [comment]
`s_useOpenAL 1` is currently required for audio capture.

**Comment by pragmader** [comment]
@zturtleman Sorry, forgot to include this flag in my issue description. In fact s_useOpenAL was set to "1" by default for me, I followed [these](https://github.com/ioquake/ioq3/blob/master/voip-readme.txt) instructions and therefore checked.

I compiled the same sources for Linux and VoIP works with exactly the same configuration there using Pulse Audio. I'm pretty sure there is something wrong with ioquake VoIP on Mac. Any thoughts?

Does anyone use the VoIP feature on Mac and it works?

**Comment by ensiform** [comment]
Have you confirmed that openal is in fact being used and working?

`s_backend` and `/soundinfo` commands?

**Comment by pragmader** [comment]
@ensiform `s_backend` returns `"base"` and `soundinfo` "command not found".
So, according to the `s_backend` I'm not using OpenAL although I set `s_useOpenAL "1"`. How can I enable OpenAL then?

**Comment by pragmader** [comment]
I found this in the logs:

```
------ Initializing Sound ------
Refusing to attempt to load library "/System/Library/Frameworks/OpenAL.framework/OpenAL": Extension not allowed.
Failed to load library: "/System/Library/Frameworks/OpenAL.framework/OpenAL".
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "coreaudio".
SDL_AudioSpec:
  Format:   AUDIO_S16LSB
  Freq:     22050
  Samples:  512
  Channels: 2
Starting SDL audio callback...
SDL audio initialized.
----- Sound Info -----
    1 stereo
16384 samples
   16 samplebits
    1 submission_chunk
22050 speed
0x7fd9cf884200 dma buffer
No background file.
----------------------
Sound initialization successful.
```

**Comment by ensiform** [comment]
The log tells you it failed to load, so someone needs to fix that on Mac.

**Comment by zturtleman** [comment]
Loading libraries was limited to *.dylib in 05858d30e8934cb14aac7d343c8328ae070bb039 to prevent mod code (QVMs) from writing and executing arbitrary code. I've added an exception for macOS system frameworks in b689515965d0d7a998a956cce863c0deb8237eb8. I've tested and VoIP recording works on macOS. Thanks for reporting the issue.

**Comment by pragmader** [comment]
Thank you very much @zturtleman !
