### ISSUE TITLE
Release 1.37 when?

### ISSUE THREAD

**Issue by grepwood** [ioquake/ioq3#365]
Just curious.

**Comment by grepwood** [comment]
@timangus Nice one, closed without explanation. I would want to provide ebuilds of ioquake3 for my own distro, but the vanilla 1.36 is way too old. It doesn't even build on i686 anymore with current compilers. I'd like to feature a codebase that's stable and has some cool features too. Any chance?

**Comment by TimeDoctor** [comment]
This has been discussed again and again, please feel free to discuss it on the forums at https://discourse.ioquake.org

**Comment by timangus** [comment]
@grepwood github is not for asking questions.
