### ISSUE TITLE
Missing bots in single player mode

### ISSUE THREAD

**Issue by umpirsky** [ioquake/ioq3#373]
I just installed it on Ubuntu 18.04, go to single player, pick the first arena against Crash, but no bot entered the arena.

**Comment by Calinou** [comment]
Which ioquake3 version are you running? Are you using a test build or did you compile it from source? The 1.36 stable version (which is from 2009) is no longer supported.

**Comment by Calinou** [comment]
Try a test build from [this page](http://ioquake3.org/get-it/test-builds/).

**Comment by umpirsky** [comment]
@Calinou Worked, thanks!
