### ISSUE TITLE
Mouse movement stutter

### ISSUE THREAD

**Issue by WSSDude** [ioquake/ioq3#377]
On my quite beefy PC, I'm experiencing some kind of microstutter when moving my mouse. 

As long as I'm not moving my mouse, everything is smooth.

This issue is much more prevelant on my laptop. No issues in this regard with vanilla engine.

PC specs:
CPU: Ryzen 2600x
RAM: 16gb DDR4
GPU: Geforce GTX 1050
OS: Windows 10 64bit 1803

Binaries built with MSYS2's MinGW 64-bit, GCC 7.3.0 for 64-bit arch.

**Comment by angrynerd** [comment]
In my expirience in_mouse -1 fixed the issue for me i hope this helps.

**Comment by angrynerd** [comment]
I would look into r_busywait and r_finish i the above disnt work

**Comment by ensiform** [comment]
That's pretty strange honestly, raw mouse is the default with sdl2 which should be the fastest on Windows.  It's possible that newer windows 10 is messing with things for older games.  Have you tried forcing windows 7 compatible mode to see if it helps

**Comment by WSSDude** [comment]
I pulled latest commits today, compiled and played - no stutter. It may have been fixed. Anyway, issue closed.
