### ISSUE TITLE
Inability to save 'Favorites' as default in the server browser

### ISSUE THREAD

**Issue by cdev-tux** [ioquake/ioq3#378]
The integer range for ui_browserMaster cvar isn't large enough to accommodate the current number of master lists, so the last member (Favorites) can't be set as default.
Increasing the integer range from 6 to 7 corrects the issue.

https://github.com/ioquake/ioq3/blob/master/code/q3_ui/ui_servers2.c#L1588

ioquake/ioq3@9f239d6

Thanks.

**Comment by ensiform** [comment]
Probably should use a define instead of a naked magic number

**Comment by zturtleman** [comment]
Fixed in 29db64070aa0bae49953bddbedbed5e317af48ba. Thanks.
