### ISSUE TITLE
ioq3ded build

### ISSUE THREAD

**Issue by a2kas** [ioquake/ioq3#384]
How to build ioq3ded.exe file? I nowhere found instructions how to do it . for building I am using Visual Studio.

**Comment by ellisgl** [comment]
Looked for "server" ?

**Comment by a2kas** [comment]
> Looked for "server" ?

where?

**Comment by ensiform** [comment]
You should build with mingw not visual studio.  The visual studio projects don't include support for the dedicated server among other features

**Comment by ensiform** [comment]
Ranking support isn't available, the file isn't used

**Comment by kungfooman** [comment]
Use this for a VS solution with everything https://github.com/jpcy/ioq3-premake-msvc

**Comment by a2kas** [comment]
`Use this for a VS solution with everything https://github.com/jpcy/ioq3-premake-msvc`

Great :) thank you so much

**Comment by richrumble** [comment]
I can't get ioq3ded to respond on Windows, Linux or Pi... I start the server, but I can't join it, even from the localhost! I'm using 64bit OS's, Win7, Ununtu (latest) and Raspberryian (latest, but isn't 64bit OS). I can use the client's to join public servers... I cannot figure it out! Sniffing via WireShark I see the challenge packets being sent by the clients, no replies from the server. If I nMap the port on the server I see status packets sent from nMap, no replies. All firewalls are off, wire lan's, and again the Local hosts 127.0.0.1 can't connect.

**Comment by a2kas** [comment]
@richrumble did you open ports?

**Comment by richrumble** [comment]
It's local Lan party style, firewalls are off, dedicated=1. I have not tried the test-builds, trying those now.

**Comment by ensiform** [comment]
Did you start a map? Test builds are mandatory at this point

**Comment by richrumble** [comment]
I've got my server.cfg with all the maps I used to run (and I have them all in my base3 dir), once the ioq3ded starts (./ioq3ded +exec server.cfg +exec q3config_server.cfg) Using test-builds did not fix the issue. Again I'm even trying 127.0.0.1... I thought the maps start automagically when using the server.cfg. 

> 5384 files in pk3 files
> execing default.cfg
> execing q3config_server.cfg
> couldn't exec autoexec.cfg
> Hunk_Clear: reset the hunk ok
> --- Common Initialization Complete ---
> Winsock Initialized
> Hostname: Rocket-PC
> IP6: ::::
> IP: 10.0.0.35
> Opening IP socket: 0.0.0.0:27960

**Comment by richrumble** [comment]
started a map... it worked... I am ashamed :( Any way to auto start a map?

**Comment by Calinou** [comment]
@richrumble I think you can add `+map q3dm1` (or similar) at the end of the command line when starting the server.

**Comment by ensiform** [comment]
Don't put +exec q3config_server, it's not necessary and ends up executing twice

**Comment by angrynerd** [comment]
There are several ways to make a map start or have a rotation and the best way i have found is to use vstrs ex typing set x1 "map q3dm1; set nextmap vstr x2". And so on at the bottom it would loop to x1. Then just run the vstr in your server config.

**Comment by TimeDoctor** [comment]
Glad everyone seems to have it working, please use https://discourse.ioquake.org/ to discuss ioquake3 dedicated server usage and suggest or make changes to our server operations guide: http://wiki.ioquake3.org/Sys_Admin_Guide
