### ISSUE TITLE
Request: libretro API spec as input/output interface

### ISSUE THREAD

**Issue by ghost** [ioquake/ioq3#388]
Optionally outsources distribution, portability, lag and toxic end-users to libretro.

Allows for more intense focus on improving the new render engine.

https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h

Split the client into a frontend & core using that API spec.

Optionally, there is a vast amount of ready frontends to choose from.

inb4: Yes. libretro does support mouse & keyboard.

**Comment by TimeDoctor** [comment]
While I would welcome another interface for new players, and I would personally think it’s cool to have ioquake3 launch on a dedicated arcade cab, I’m not sure it would make sense with the spirit of this project.
