### ISSUE TITLE
Any legacy archives of ioq3?

### ISSUE THREAD

**Issue by hokuco** [ioquake/ioq3#391]
I was recently working on a project requiring an older version of ioquake,(specifically the version that was on icculus.org) does anyone have the svn stuff that was originally hosted here:  `https://svn.icculus.org/quake3/trunk/`  ?

**Comment by TimeDoctor** [comment]
You can specify the revision to check out of SVN or do the same thing through the github interface https://svn.icculus.org/quake3/trunk/?pathrev=2398
