### ISSUE TITLE
What do the `vm_ui`, `vm_game` and `vm_cgame` settings actually do?

### ISSUE THREAD

**Issue by acheronfail** [ioquake/ioq3#399]
I've been looking all over for documentation on server settings, but I can't find any docs or explanations for the following settings:

```
set vm_cgame
set vm_game 
set vm_ui
```

From what I have found, these settings force ioquake3 to use shared libraries instead of "QVM"s (<- not sure what these actually are).
I've found conflicting examples, some say `vm_game 1` means use shared libraries, and some say that `vm_game 0` means use shared libraries.

Are these documented anywhere? Or can anyone give me an explanation on what they actually do?

**Comment by jpcy** [comment]
https://github.com/ioquake/ioq3/blob/master/code/qcommon/qcommon.h#L334

VMI_NATIVE (0) is shared libs / dlls.
VMI_BYTECODE (1) is qvm bytecode using the interpreter (slow).
VMI_COMPILED (2) is qvm bytecode using various CPU instruction sets (default, fast).

**Comment by ensiform** [comment]
The issues list isn't for asking questions, there is forums/discord/irc for that 😉

**Comment by acheronfail** [comment]
Awesome, thanks 😊 

Next time I’ll use the discord 👍
