### ISSUE TITLE
ioq3ded: User needs write access to fs_homepath

### ISSUE THREAD

**Issue by greg-kennedy** [ioquake/ioq3#412]
I am trying to run ioq3ded as a non-root user, but reading from a shared fs_homepath owned by another user (root).  This seems like it should work fine, as the server really shouldn't need write access to the common game folder - just read the shared data files and go.  However it does look like there are a few files getting written to this location.  Specifically, game start-up shows these lines when launched without write permissions:

    WARNING: Couldn't open logfile: games.log
    ...
    Couldn't write q3config_server.cfg.

Could we have these written somewhere else, like a temp path or something?  Or, provide an override for these filenames so I can redirect them somewhere else?

**Comment by ensiform** [comment]
fs_homepath is intended to be your writable path. Everything else should be in fs_basepath location that is read only.

**Comment by greg-kennedy** [comment]
Ah, thanks, that's exactly what I needed to find!
