### ISSUE TITLE
Most up-to-date OSS Q3?

### ISSUE THREAD

**Issue by dm17** [ioquake/ioq3#413]
Just getting back into it after years and wasn't sure where to ask:

Is ioquake the most recent & maintained OSS quake project? I was checking Warsow and OpenArena, and they don't seem to get as many commits. 

Second, has ioquake or any other OSS gotten contributions from QuakeLive? I'm guessing QL development ended some time ago - and if we weren't only counting OSS it would be the most maintained quake project, right?

Thanks for all your efforts! :)

**Comment by TimeDoctor** [comment]
This is the most up-to-date Quake 3 project. OA uses ioquake3 code, but as far as I know is just a new game based on our code. Warsow, I don’t think they use Quake 3 code. Quake Live is still closed source software that can’t use our advancements unless they open the source code. In any case, please keep this area for issues and discussion on the discourse forums, discord, and IRC.
