### ISSUE TITLE
Resolve issues found by PVS (static analysis tool)

### ISSUE THREAD

**Issue by demoth** [ioquake/ioq3#415]
Hi 

I have run PVS against the code. Attaching the report.

https://docs.google.com/spreadsheets/d/1wgp0v5ycOYL8b2p-VZLi9bHb9LCDoy7D1YWFaLjk2So/edit?usp=sharing

**Comment by TimeDoctor** [comment]
Please feel free to discuss strategies for fixing issues found with scanning utilities on our forums at discourse.ioquake.org . This report as it is, especially including third-party code we don’t control, is not tremendously helpful as an issue although I appreciate the time you took to run it.

**Comment by demoth** [comment]
@TimeDoctor The idea behind this exercise was to highlight suspicious places in the code so other may take a look and improve.
I agree thirdparty code is not very interesting - I filtered it out.

**Comment by ensiform** [comment]
A lot of these are actually false positives anyway.
