### ISSUE TITLE
Mac OS X: App not 64-bit optimized for Mac OS Catalina?

### ISSUE THREAD

**Issue by sxflynn** [ioquake/ioq3#418]
When I launch ioquake on Mac OS Mojave, I get a warning that says the software is not optimized, which basically means it is not 64-bit. As of the next Mac OS version Catalina, it will no longer launch.

**Comment by TimeDoctor** [comment]
Is this a version of ioquake3 compiled on your computer or one downloaded from ioquake3.org recently?

**Comment by timotgl** [comment]
I was able to run it after downloading Xcode 11 for the Catalina Beta and compiling with `./make-macosx.sh x86_64`.

However, something seemed off the with OpenGL support. Extremely low FPS and my 4k monitor only showed the game in the bottom left quadrant of the screen (resolution in game set to 1920x1080).

Running the universal binary before on Mojave didn't have these issues.

**Comment by sxflynn** [comment]
> Is this a version of ioquake3 compiled on your computer or one downloaded from ioquake3.org recently?

I downloaded it from ioquake3.org recently. Would it be possible for someone with X-Code know-how to recompile as 64 bit?

**Comment by ensiform** [comment]
There are no "recent" downloads due to security issue

**Comment by tomkidd** [comment]
Yeah I'm running a version on Catalina just now compiled on the command line from the makefile and I'm getting the issue with the screen being in the lower left-hand quarter of the screen on my 2014 MBP. 

And I'm seeing the same issue in a few other games from source that I didn't have the issue with prior to Catalina - like yquake2.

Were I to guess I'd say something changed with how screen size calculations work, possibly issue with Retina display (everything needs to be multiplied by 2 maybe?) as I just hooked it up to a 1080p monitor and mirrored displays and then did not experience the issue.

**Comment by TimeDoctor** [comment]
To be clear for anyone casually browsing this thread, this is the relevant security information: https://ioquake3.org/2019/06/13/ioquake3-security-notice-06-13-19-test-builds-possibly-compromised/

**Comment by diegoulloao** [comment]
Someone who has achieved to compile ioquake3fe-1.36 file to x64?

**Comment by tomkidd** [comment]
@diegoulloao If you're asking if ioquake3 can be compiled to x64 on macOS, yes, right now it builds via the makefile shell script

`./make-macosx.sh x86_64`

If you're asking if there are precompiled binaries for x64 on macOS, there were nightly test builds happening until they took them down due to a security issue with their automated build software. 

So yes there were but they're offline at the moment.

**Comment by TimeDoctor** [comment]
the ioquake3fe was a mac-specific front-end that we hoped to replace with a cross-platform launcher, unfortunately the launcher project never got off the ground and should probably be scrapped and replaced at this point

**Comment by diegoulloao** [comment]
> @diegoulloao If you're asking if ioquake3 can be compiled to x64 on macOS, yes, right now it builds via the makefile shell script
> 
> `./make-macosx.sh x86_64`
> 
> If you're asking if there are precompiled binaries for x64 on macOS, there were nightly test builds happening until they took them down due to a security issue with their automated build software.
> 
> So yes there were but they're offline at the moment.

In ioquake3 folder are included 2 files:
-  ioquake3-1.36 (game executable app)
-  ioquake3fe-1.36 (I think tool for run servers)

![Captura de Pantalla 2019-10-12 a la(s) 01 25 36](https://user-images.githubusercontent.com/45423661/66694903-7b9ee480-ec8f-11e9-9590-84ce38fafdcf.png)

I already have compiled the game executable for 64-bits, but I don't know how to get or compile the other.

**Comment by andersonbatista333** [comment]
Hi Folks!

After downloaded the branch 3318 from https://github.com/ioquake/ioq3 and follow instructions to compile from source with xcode 10.3 build 10G8, see below the result;
./make-macosx.sh x86_64
Building x86_64 Client/Dedicated Server against ""

Building in build/release-darwin-x86_64:
  PLATFORM: darwin
  ARCH: x86_64
  VERSION: 1.36
  COMPILE_PLATFORM: darwin
  COMPILE_ARCH: x86_64
  HAVE_VM_COMPILED: true
  PKG_CONFIG: pkg-config
  CC: cc
...
Creating bundle 'build/release-darwin-x86_64/ioquake3.app'
with architectures:
 x86_64

When compile is done and checked thats the newer binaries is x86_64, copy ioquake3.app to Applications as follows;

...
file build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/ioquake3 
build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/ioquake3: Mach-O universal binary with 1 architecture: [x86_64:Mach-O 64-bit executable x86_64]
build/release-darwin-x86_64/ioquake3.app/Contents/MacOS/ioquake3 (for architecture x86_64):	Mach-O 64-bit executable x86_64

![image](https://user-images.githubusercontent.com/23341075/66720503-d93c4980-edd3-11e9-97f6-0055388f18fc.png)
![image](https://user-images.githubusercontent.com/23341075/66720535-494acf80-edd4-11e9-9b28-a2061e474047.png)

After executing ioquake3 from Applications folder, remember to set Defaults configurations on Setup menu due incorrect resolution and/or screen settings;

![image](https://user-images.githubusercontent.com/23341075/66720583-03dad200-edd5-11e9-8ffe-9565e1bc4528.png)

Enjoy the game!

**Comment by diegoulloao** [comment]
Hey you guys!

**Please check: https://github.com/diegoulloao/ioquake3-mac-install**

**Comment by TimeDoctor** [comment]
@diegoulloao this is the ioquake3 project, please do not spam your project here in every thread. I understand you are proud of it, but it is not this project. If you would like to contribute to this project, please open a pull request.

**Comment by TimeDoctor** [comment]
This issue has also been resolved, please let me know if there is still an issue, compiling by hand gives you a 64bit binary and we have other issues open for specific Catalina 10.15 issues.

**Comment by diegoulloao** [comment]
@TimeDoctor, sorry my comment has been understood as spam or invasion, that was not the purpose. Real purpose is give to these who are looking for a solution, an easy way to get trough it.

Glad issue has been also resolved.
Regards.
