### ISSUE TITLE
Windows build instructions link is down

### ISSUE THREAD

**Issue by sryze** [ioquake/ioq3#421]
The Windows build instructions link mentioned in the README is not working anymore:

http://wiki.ioquake3.org/Building_ioquake3

There is a copy in the web archive though:

https://web.archive.org/web/20190522123759/wiki.ioquake3.org/Building_ioquake3

**Comment by TimeDoctor** [comment]
https://ioquake3.org/2019/06/13/ioquake3-security-notice-06-13-19-test-builds-possibly-compromised/

The wiki will be offline until I restore under Docker.
