### ISSUE TITLE
MacOS Catalina

### ISSUE THREAD

**Issue by DaveParke** [ioquake/ioq3#430]
Hi - upgraded today to Catalina from Mojave.  Had the same problem others had with the resolution and the game not filling the screen.  I was able to resolve it by setting the resolution to half my resolution.  Sadly, after getting it to work I fiddled around with other resolutions - eventually came upon one where I couldn't see enough of the screen to change it back (stupid me).  Does anyone know who to change resolution back without being in game? (or is there a config file somewhere I could edit or delete)?  Thank you!

**Comment by DaveParke** [comment]
Hi - fixed the problem.  Went into display settings, turned off "Default for display" and switch to "Scaled" > "More Space".  I was able to see enough of the screen to change it back.

**Comment by TimeDoctor** [comment]
There are a few other ways out of this situation as well. You can also manually edit the configuration files in /Users/YOURNAME/Library/Application Support/Quake3/ or by manually launching the executable inside the .app bundle with the appropriate command-line options.
