### ISSUE TITLE
No difference with standard renderer

### ISSUE THREAD

**Issue by FlamesoFF** [ioquake/ioq3#431]
No difference with standard renderer.

`cl_renderer == "opengl2"`

OS: Windows 10
Game version: Steam latest.
![image](https://user-images.githubusercontent.com/5371279/68909568-01aac100-074f-11ea-8726-38fa5012ec66.png)

**Comment by TimeDoctor** [comment]
you may need to change options to see a difference: http://web.archive.org/web/20190428180208/http://wiki.ioquake3.org/Players_Guide#Advanced_OpenGL_2_renderer_settings

**Comment by FlamesoFF** [comment]
@TimeDoctor No. 
I just installed latest test build from the link you provided. Now it's working.
Why this build is not in the repository releases? It's impossible to find it with Google.

**Comment by TimeDoctor** [comment]
https://ioquake3.org/2019/06/13/ioquake3-security-notice-06-13-19-test-builds-possibly-compromised/

**Comment by FlamesoFF** [comment]
@TimeDoctor How about not to use this "Jenkins" thing and simply compile it manually?
