### ISSUE TITLE
r_displayRefresh gives no effect.

### ISSUE THREAD

**Issue by FlamesoFF** [ioquake/ioq3#433]
Monitor: 75Hz
***
`r_displayRefresh` gives no effect. Refresh rate fixed to 60Hz.
In other games it's 75.

config:
```
r_mode -1
r_customWidth 1920
r_customHeight 1080
r_displayRefresh 77
```

Also `r_mode -2` does not help.

Display settings:
![image](https://user-images.githubusercontent.com/5371279/69083930-64e46e00-0a43-11ea-8566-219b770a3d44.png)

In other engines (default and CNQ3) it works normally and monitor's refresh rate detected correctly.

**Comment by KuehnhammerTobias** [comment]
Eventually try connecting via DisplayPort first, if available.

**Comment by TimeDoctor** [comment]
is this a version of ioquake3 compiled from source?

**Comment by Calinou** [comment]
You could also use a borderless fullscreen window (`r_noborder 1`) to prevent ioquake3 from changing your display's refresh rate.

**Comment by FlamesoFF** [comment]
> You could also use a borderless fullscreen window (`r_noborder 1`) to prevent ioquake3 from changing your display's refresh rate.

And get massive input lag? No, thanks.

**Comment by Calinou** [comment]
@FlamesoFF Using windowed mode doesn't add any meaningful amount of input lag, unless your window manager happens to be enforcing V-Sync somehow.

**Comment by FlamesoFF** [comment]
@Calinou 
> Using windowed mode doesn't add any meaningful amount of input lag
Of course it does.
> For reference, many competitive CS:GO players now use borderless window mode
Omg, please do't argue if you don't understand the topic. Competitive players could use it on stream for example, to be able to read chat, for example, but no pros are using it on tournament, because it gives heavy input lag.

Only modern Directx flip fullscreen mode can allow to play without additional input lag, which is not supporter by this 2 games neither.
