### ISSUE TITLE
The wiki is offline!

### ISSUE THREAD

**Issue by rhulha** [ioquake/ioq3#437]
http://wiki.ioquake3.org is offline for me...

Please fix.

**Comment by TimeDoctor** [comment]
We are aware, it will return.

**Comment by csallen1204** [comment]
Perhaps it might be easier to move the wiki from ioquake3.org to GitHub?

**Comment by NuclearMonster** [comment]
That’s not a bad idea, but it isn’t one we will choose at this time.
