### ISSUE TITLE
the building instruction page cannot be opened

### ISSUE THREAD

**Issue by smartmaster** [ioquake/ioq3#438]
http://wiki.ioquake3.org/Building_ioquake3

This page isn’t workingwiki.ioquake3.org didn’t send any data.
ERR_EMPTY_RESPONSE

> 
> For Windows,
> 
> Please refer to the excellent instructions here: http://wiki.ioquake3.org/Building_ioquake3

**Comment by TimeDoctor** [comment]
We are aware that the wiki is offline, please use the web archive until it returns: http://web.archive.org/web/20180521181750/http://wiki.ioquake3.org/Main_Page
