### ISSUE TITLE
Run/walk key bind doesn't work

### ISSUE THREAD

**Issue by bashmentarium** [ioquake/ioq3#439]
Whatever key I bind for the run/walk command, I just don't move forward. I've quickly started a new game as soon as I installed, chose a map, added a bot and... I can't move forward. Left, right, jump, crouches, shoot - everything else is alright. I've restarted numerous times both the game and the computer. Re-installed it a couple of times. I've also tried binding a ton of other keys to see maybe something is wrong with my keyboard. Everything is fine. It may seem like a joke, but as far as you can see, I've got plenty of "w", "e", "r", "t" so you know my keyboard actually works.

UPDATE: I've downloaded the Defrag mode, and in that mode the forward button bind works fine.

**Comment by KuehnhammerTobias** [comment]
run/walk is something different than move forward. So now I don't understand what actually doesn't work. Moving forward, or walking instead of running.
Also be sure to get the latest test build, or even better compile the latest source code from repositoy

**Comment by bashmentarium** [comment]
I am so sorry, I couldn't sleep that night and my concentration was at 0 because I couldn't see the difference between the "move forward" and "run/walk" toggler. Thank you for you response. Could you please delete this mess of an issue I have pointlessly opened?
