### ISSUE TITLE
openGL2 issue on MAC OS X

### ISSUE THREAD

**Issue by Wouam1** [ioquake/ioq3#445]
Hi everyone, I have an openGL2 issue on MAC OS X Catalina 10.15.3 on a Macbook air 2015..
When I write 'seta cl_renderer "opengl2"' in autoexec.cfg I have this error or a black screen if I ignore it(r_ignoreGLErrors 1) but if it's 'seta cl_renderer "opengl1"' the game work..
Any ideas?
Thanks

Here the crashlog:

----- Client Initialization -----
----- Initializing Renderer ----
Trying to load "renderer_opengl2_x86_64.dylib" from "/Applications/ioquake3/ioquake3SDL2.0.10.app/Contents/MacOS"...
-------------------------------
QKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "cocoa"
Initializing OpenGL display
Display aspect: 1.600
...setting mode -1: 1440 900
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext failed: Failed creating OpenGL pixel format
Reverting to default context
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '800x500 1024x640 1152x720 1280x800 1440x900 720x480 640x480 800x600 1024x768'
GL_RENDERER: Intel(R) HD Graphics 6000
Initializing OpenGL extensions
...GL_EXT_texture_compression_s3tc not found
...GL_S3_s3tc not found
...using GL_EXT_texture_filter_anisotropic (max: 16)
...using GL_SGIS_texture_edge_clamp
...using GL_ARB_framebuffer_object
...using GL_ARB_vertex_array_object
...using GL_ARB_texture_float
...using GL_ARB_depth_clamp
...ignoring GL_ARB_seamless_cube_map
...using GLSL version 4.10
...GL_NVX_gpu_memory_info not found
...GL_ATI_meminfo not found
...GL_ARB_texture_compression_rgtc not found
...GL_ARB_texture_compression_bptc not found
...GL_EXT_direct_state_access not found
----- Client Shutdown (Client fatal crashed: GL_CheckErrors: GL_INVALID_ENUM in code/renderergl2/tr_image.c at line 2226) -----
RE_Shutdown( 1 )
Hunk_Clear: reset the hunk ok
-----------------------
GL_CheckErrors: GL_INVALID_ENUM in code/renderergl2/tr_image.c at line 2226

**Comment by zturtleman** [comment]
Looks like the error is caught here: https://github.com/ioquake/ioq3/blob/f2c61c14c4ee3d79907cdac5251706c2f96a4901/code/renderergl2/tr_image.c#L2226

Unfortunately it could be caused by many different functions and probably need to add `GL_CheckErrors();` at beginning of `R_CreateImage2` function and after have gl*() line to figure out where the error is coming from.
