### ISSUE TITLE
rail gun is constantly playing hit sound

### ISSUE THREAD

**Issue by freder** [ioquake/ioq3#451]
whenever someone has the rial gun selected, it emits the hit sound (at ~5 beats per second). – is that a bug?

- ioquake 1.36
- macos 10.14.6

**Comment by TimeDoctor** [comment]
unfortunately any build from the website is very old right now, when we get a new build up it may work better for you.

**Comment by freder** [comment]
I just built `master`, and it seems to be fixed there. however, there seem to be other problems now.

**Comment by TimeDoctor** [comment]
let us know what you've run into

**Comment by Calinou** [comment]
This issue should probably be closed, since it's resolved in `master`.

**Comment by TimeDoctor** [comment]
Ok, please open a new issue for anything else you find :)
