### ISSUE TITLE
Windows build instructions

### ISSUE THREAD

**Issue by victorbstan** [ioquake/ioq3#452]
Hello, the readme points to http://wiki.ioquake3.org/Building_ioquake3 which is not accessible. How do I build on Windows? Could the instructions be included in the main repository?

**Comment by TimeDoctor** [comment]
https://web.archive.org/web/20190508064013/https://wiki.ioquake3.org/Main_Page

https://ioquake3.org/2019/06/13/ioquake3-security-notice-06-13-19-test-builds-possibly-compromised/
