### ISSUE TITLE
Rotating a model so it "sticks" to a plane

### ISSUE THREAD

**Issue by x3c** [ioquake/ioq3#453]
Hello guys,

No math background here but I figured someone here has the answer.

I'm working on an ioq3 mod and I need to make a model "stick" to a plane it's standing on, while controlling its yaw - basically I'm trying to add an NPC that will head to a particular X/Y location but must be crawling on the ground plane it's standing on, so I need to figure out pitch and roll from the plane's normal and the model's yaw.

For the same of simplicity, let's say that I just have the lower.md3 model which happens to be a spider, so it crawls in a circle, on an inclined plane.

The heading (yaw) constantly changes since it has to be crawling in a circle, and I control that heading.  But for the model to appear to be crawling on the inclinde plane, I need to adjust model's pitch and roll every time I adjust its yaw.

I have no math background so it's pretty much impossible to guess.  I've looked around in ioq3 source and there simply doesn't seem to be a case where something similar happens - the only case  I've stumbled upon were the proximity mines who stick to a surface - but their yaw seems to be fixed to 0 or something.  Close but no cigar.

Thanks for any help or at least pointers, heh.

**Comment by TimeDoctor** [comment]
Please discuss ioquake3 game/mod development on https://discourse.ioquake.org, this is for issues with the engine itself, but I'm excited to hear more about your mod!
