### ISSUE TITLE
Can we improve the installation doc for *nix?

### ISSUE THREAD

**Issue by dm17** [ioquake/ioq3#455]
I've compiled & installed it, but I'm not sure how to run it. I know I need pk0.pk3, but ioquake3.x86_64 isn't executable - so I'm guessing I'm missing other stuff in order to run q3. What else is needed to run q3 after a compilation & install (as per your README)? I'm on Linux.

**Comment by Calinou** [comment]
> but ioquake3.x86_64 isn't executable

Some file managers can report it as a shared library if it was built as a position-independent executable. Try running it from a terminal instead (`./ioquake3.x86_64`).

**Comment by dm17** [comment]
Just tried in bash & zsh - no such file or dir when doing ./ioquake3.x86_64

**Comment by dm17** [comment]
> Nothing special is needed, as long as `pak0.pk3`-`pak8.pk3` are present in the `baseq3` folder

That should be added to the README ;)
OK, not sure why it worked now... I think I did the full path before which doesn't work:
./opt/quake3/ioquake3.x86_64

**Comment by Calinou** [comment]
@dm17 I guess ioquake3 doesn't try to check files relative to the basepath, but will check relative to your current working directory instead. That can be worked around by placing the PK3 files in `$HOME/.q3a/baseq3/` instead (create folders if needed).

**Comment by dm17** [comment]
Should probably start a new thread for this... But any idea if it works with tiling window managers? I get nothing on screen when it starts, a bit of graphics corruption across the bottom of the screen, but I can hear it working... And just type /quit... And see no errors in the quake3 log:

SSE instruction set enabled
----- FS_Startup -----
We are looking in the current search path:
/home/box/.q3a/baseq3
./baseq3
./baseq3/pak8.pk3 (9 files)
./baseq3/pak7.pk3 (4 files)
./baseq3/pak6.pk3 (64 files)
./baseq3/pak5.pk3 (7 files)
./baseq3/pak4.pk3 (272 files)
./baseq3/pak3.pk3 (4 files)
./baseq3/pak2.pk3 (148 files)
./baseq3/pak1.pk3 (26 files)
./baseq3/pak0.pk3 (3539 files)
----------------------
4073 files in pk3 files
execing default.cfg
execing q3config.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
----- Client Initialization -----
----- Initializing Renderer ----
Trying to load "renderer_opengl2_x86_64.so" from "."...
-------------------------------
QKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.778
...setting mode -2: 2560 1440
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '1024x576 1280x720 1366x768 1600x900 1680x945 1920x1080 2048x1152 2560x1440 1360x768 848x4
GL_RENDERER: Radeon RX 580 Series (POLARIS10, DRM 3.36.0, 5.6.18_1, LLVM 10.0.0)
Initializing OpenGL extensions
...GL_EXT_texture_compression_s3tc not found
...ignoring GL_S3_s3tc
...ignoring GL_EXT_texture_filter_anisotropic
...using GL_SGIS_texture_edge_clamp
...using GL_ARB_framebuffer_object
...using GL_ARB_vertex_array_object
...using GL_ARB_texture_float
...using GL_ARB_depth_clamp
...ignoring GL_ARB_seamless_cube_map
...using GLSL version 4.60
...using GL_NVX_gpu_memory_info
...ignoring GL_ATI_meminfo
...ignoring GL_ARB_texture_compression_rgtc
...ignoring GL_ARB_texture_compression_bptc
...GL_EXT_direct_state_access not found
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 114 GLSL shaders (48 gen 42 light 24 etc) in  0.06 seconds
------- R_InitVaos -------
Initializing Shaders
PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
MODE: -2, 2560 x 1440 fullscreen hz:N/A
GAMMA: hardware w/ 1 overbright bits
texturemode: GL_LINEAR_MIPMAP_NEAREST
picmip: 1
texture bits: 0
compiled vertex arrays: disabled
texenv add: enabled
compressed textures: disabled
----- finished R_Init -----
------ Initializing Sound ------
Trying to load "libopenal.so.1"...
Allocated 96 sources.
OpenAL default capture device is 'ALSA Default'
OpenAL capture device opened.
OpenAL info:
  Vendor:         OpenAL Community
  Version:        1.1 ALSOFT 1.20.1
  Renderer:       OpenAL Soft
  AL Extensions:  AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_I
_SOFT_bformat_ex AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_direct_ch
rce_resampler AL_SOFT_source_spatialize
  ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disco
  Device:         ALSA Default
  Available Devices:
ALSA Default
HDA ATI HDMI, HDMI 0 (CARD=HDMI,DEV=3)
HDA ATI HDMI, HDMI 1 (CARD=HDMI,DEV=7)
HDA ATI HDMI, HDMI 2 (CARD=HDMI,DEV=8)
HDA ATI HDMI, HDMI 3 (CARD=HDMI,DEV=9)
HDA ATI HDMI, HDMI 4 (CARD=HDMI,DEV=10)
HDA ATI HDMI, HDMI 5 (CARD=HDMI,DEV=11)
HD-Audio Generic, ALCS1200A Analog (CARD=Generic,DEV=0)
  Input Device:   ALSA Default
  Available Input Devices:
ALSA Default
HD-Audio Generic, ALCS1200A Analog (CARD=Generic,DEV=0)
HD-Audio Generic, ALCS1200A Alt Analog (CARD=Generic,DEV=2)
Sound initialization successful.
--------------------------------
Loading vm file vm/ui.qvm...
File "vm/ui.qvm" found in "./baseq3/pak8.pk3"
VM file ui compiled to 991377 bytes of code
ui loaded in 1688576 bytes on the hunk
35 arenas parsed
32 bots parsed
--- Common Initialization Complete ---
IP: 127.0.0.1
IP: 192.168.1.39
Opening IP6 socket: [::]:27960
Opening IP socket: 0.0.0.0:27960
----- Client Shutdown (Received signal 15) -----
RE_Shutdown( 1 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
Hunk_Clear: reset the hunk ok
OpenAL capture device closed.

**Comment by TimeDoctor** [comment]
Hi, you’re right that the readme and other information in the repo is out of date. The appropriate place to have discussions about running the game is on our forums (you can even oauth with GitHub) so that others can still benefit from anything you learn in the future. Please find our forums at https://discourse.ioquake.org

**Comment by NuclearMonster** [comment]
Sorry for the extremely late reply. I wanted to note that some quick research shows that the Signal 15 most likely is coming from something external to ioquake3 killing ioquake3. No idea if tiling WM is doing it since we don't have more information from the system. Best thing I can think of is to try a different WM and open a thread on our forums to discuss the issue if it persists through a different WM. Please also list what distribution you're using and if you compiled ioquake3 from source or what. You can even log in with github through our forums.
