### ISSUE TITLE
Crash after adding 28 bots (G_ALLOC: failed on allocation of 9088 Bytes)

### ISSUE THREAD

**Issue by isaacbernat** [ioquake/ioq3#457]
I started adding bots using the console (`/addbot sarge`) after setting an upperlimit of `/sv_maxclients 50` playing on Q3DM1 but it crashes after 28 bots (see screenshots on console logs after it crashes).

I increased `hunkmegs` on the console, re-compiled with `MAX_RELIABLE_COMMANDS` set to 128 in `code/qcommon/qcommon.h` and many things I found on the internet but nothing worked so far. Any ideas which parameters I should tune to allow more bots? Thanks!
![IMG_20200628_191713](https://user-images.githubusercontent.com/2509809/85957693-da2c0000-b98f-11ea-81ae-65e4795ce7c6.jpg)
![IMG_20200628_191409](https://user-images.githubusercontent.com/2509809/85957697-dc8e5a00-b98f-11ea-9316-c415bdaeae4a.jpg)

**Comment by pdc-frans** [comment]
28 bots? Is this a hardlimit?

**Comment by zturtleman** [comment]
You can add more bots by increasing the game memory pool size for G_Alloc. It's controlled by `POOLSIZE` in code/game/g_mem.c. https://github.com/ioquake/ioq3/blob/f2c61c14c4ee3d79907cdac5251706c2f96a4901/code/game/g_mem.c#L31-L44

**Comment by isaacbernat** [comment]
@zturtleman thanks for the comments. I recompiled again for windows x86 and tried with a bigger poolsize (1024*1024) but it seems to crash at the same point as before (see screenshots). Any ideas how else I could fix this?
![IMG_20200705_224532](https://user-images.githubusercontent.com/2509809/86542273-a1060980-bf14-11ea-95bf-82405c5c5b9c.jpg)

Trying with the pre-compiled ioquake3 I already had installed (i.e. without the memory modifications mentioned), I got some crash logs (see attachment).
![IMG_20200705_225420](https://user-images.githubusercontent.com/2509809/86542285-b9762400-bf14-11ea-85b3-b6ec5aa7b80a.jpg)
[crash_logs.txt](https://github.com/ioquake/ioq3/files/4875668/crash_logs.txt)

I'd like to add bots to create a videoclip similar to this https://www.youtube.com/watch?v=VHNfvFOBC0A so I think networking shouldn't be an issue. If all the clients use the version compiled with additional commands/memory it should not be a problem right? Thanks!

**Comment by zturtleman** [comment]
`code/game/g_mem.c` is part of qagame.qvm not the engine executable. Make sure you add `build/release-mingw*/baseq3/vm/qagame.qvm` to `baseq3/vm/qagame.qvm` in your Quake 3 directory and new engine should use it. Old engine may require zipping "vm/qagame.qvm" and place in baseq3 as zzz_qagame-more-bots.pk3.

**Comment by isaacbernat** [comment]
@zturtleman Excellent! I added 50 bots now and it's working fine :D
