### ISSUE TITLE
Static cross-compiling on Linux for Windows

### ISSUE THREAD

**Issue by x3c** [ioquake/ioq3#458]
Hello guys,

Trying to make it work, but the more progress I make, the more hacky and ugly it becomes.  Million different libs to specify manually in particular orders, basically it seems less and less a viable way of doing it.

My goal is to produce an ioq3 Windows 64 bit static binary that will just run on Windows.  My Linux environment is Debian 10 / 64 bit.

I've tried different approches, what the ioq3 Makefile suggests (PLATFORM/ARCH), I tried the MXE cross compiling environment.

Maybe I'm missing something obvious?  Note that I'd like a STATIC Windows binary, including all the things such as curl, SDL and whatnot.

Any help would be welcome.

**Comment by Calinou** [comment]
Out of curiosity, why do you want a static binary on Windows? You'll need to carry the game data alongside anyway...

**Comment by x3c** [comment]
Compression and file size are irrelevant to me at this point.  The final binary can very well be 1 gigabyte in size, that's perfectly fine, all I want is to be able to test it on a variety of windows boxes.  By the time I get my project ready for distribution, I will figure out a better way, not to mention the source code will be distributed along with it, so maybe someone will come up with a better suggestion.

But for now, I want a single binary, so I can test it myself and maybe have a few friends test it.

As for the assets, they are of course in separate files and that's fine, as well.

I just want to make sure my binary will work on any reasonable windows box without me having to worry about what kind of SDL it has installed somewhere etc.  Or if their version of freetype is incompatible.  Static linking solves this headache as far as I know.

**Comment by Calinou** [comment]
@x3c I mean, you can dynamically link those libraries and bundle DLL files.
