### ISSUE TITLE
Cross compiling for Windows - cannot find vmMain in cgame.dll

### ISSUE THREAD

**Issue by x3c** [ioquake/ioq3#460]
Running Debian 10, cross compiled using MINGW32 for Windows x86_64 succesfully.

Running with wine (no windows box handy), I get the following error:
```----- finished R_Init -----
Try loading dll file <path>\uix86_64.dll
Loading DLL file: <path>\uix86_64.dll
Sys_LoadGameDll(<path>\uix86_64.dll) found vmMain function at 000000006BD421B0
^1file not found: scripts/arenas.txt
0 arenas parsed
32 bots parsed
Try loading dll file <path>\cgamex86_64.dll
Loading DLL file: <path>\cgamex86_64.dll
Sys_LoadGameDll(<path>\cgamex86_64.dll) failed to find vmMain function:
"Failed loading vmMain: Procedure not found.
" !
Failed loading dll, trying next
********************
ERROR: VM_Create on cgame failed
********************
```

But when I use "nm" on both DLL's they both have vmMain:

$ nm uix86_64.dll | grep vmMain
```000000006bd421b0 T vmMain```

$ nm cgamex86_64.dll | grep vmMain
```00000000702413b0 T vmMain```

It actually works fine in the UI, I can navigate the options etc.  Soon as I connect to a server - I get the error.

I find it very complicated to trace/debug anything considering it's under wine - can't gdb and whatnot.

Is there any way to just skip all the VM stuff?  I'd be perfectly fine with just having one monolithic .exe (but I don't have a PhD in ioq3 Makefiling unfortunately).

Any idea where I should start looking?  Thanks guys!

**Comment by x3c** [comment]
I actually get the same problem with initializing the renderer (error is "Can't load symbol GetRefAPI"), unless I use USE_RENDERER_DLOPEN=0 when compiling.

**Comment by Calinou** [comment]
> Is there any way to just skip all the VM stuff? I'd be perfectly fine with just having one monolithic .exe (but I don't have a PhD in ioq3 Makefiling unfortunately).

id Tech 3 was built around the platform-independent QVM concept (`.qvm` files), but building from source will give you platform-specific `.dll` files (or `.so` on Linux). Either way, I'm not sure if this is what's actually causing the issue here.

Maybe you could set up a Windows VM to see whether WINE is causing issues here.

**Comment by x3c** [comment]
I reduced the problem to: "compile ioq3 on Linux for Windows_64 with BUILD_STANDALONE=1 BUILD_MISSIONPACK=0 BUILD_SERVER=0 BUILD_GAME_QVM=0  and run it under wine"

It will fail with the vanilla ioq3 github master branch at loading the renderer .dll.  If you compile with USE_RENDERER_DLOPEN=0 it will succesfully load the UI dll then fail at the CGAME dll (it uses SDL_LoadFunction() which fails, to be honest I haven't looked further inside SDL).

Not sure if it's a wine or ioq3 issue.

**Comment by x3c** [comment]
I don't even get past loading the UI DLL on a Win10 Home 64 in a Virtualbox.

Anyone manages to cross-compile a _standalone_ build of ioq3 for Windows on Linux?  Regular builds work since they require pakX.pk3 from ID and these contain the cgame/qagame/ui QVMs that will be executed.

**Comment by x3c** [comment]
Actually having the the same issues with compiling on Win64 natively, with Cygwin / MinGW32.  Don't get past trying to load UI DLL.

**Comment by ensiform** [comment]
This sounds to me like there's a problem with your build tools not properly marking the vmMain and dllentry as exported symbols fully.

**Comment by x3c** [comment]
The issue was https://github.com/DaveGamble/cJSON that I added (the cJSON.c and the cJSON.h files) to the ioq3 code base.
It was breaking dynamic loading of the DLL on Windows for some reason.  I never figured out how to fix it and just removed cJSON for the time being.

**Comment by NuclearMonster** [comment]
Glad you got it going. Sounds like this isn’t an issue with ioquake3, please reopen if there is something we need to address.
