### ISSUE TITLE
No Wide Area resolutions

### ISSUE THREAD

**Issue by tkoeck** [ioquake/ioq3#464]
There are no wide are resolutions, e.g. QHD, available in the ingame configuration.

**Comment by Calinou** [comment]
You can enter `/r_mode -2` in the console then `/vid_restart` to use the desktop resolution. Alternatively, you can use `/r_mode -1; r_customwidth 2560; r_customheight 1440` then `/vid_restart`.

**Comment by tkoeck** [comment]
Yes I thought something like about that but maybe also newer resolutions should be select-able in the GUI.

**Comment by ensiform** [comment]
The GUI is controlled by the mod you have running so it's independent of ioquake3.

**Comment by tkoeck** [comment]
Good to know. Thanks for the information.

**Comment by zturtleman** [comment]
Note: ioquake3's baseq3 and missionpack UI mod code support displaying all monitor resolutions but you have to compile ioquake3 yourself to get the updated `ui.qvm` files.
