### ISSUE TITLE
this all it does is changes the main menu an such?

### ISSUE THREAD

**Issue by DOOMMARINE117** [ioquake/ioq3#467]
is there excutable or all i need my main quake 3 arena excuteable? 

did ioquake3 had executable or am i thinking another one that its own launcher?

thsi supports bots an widescreen right?

**Comment by Calinou** [comment]
> is there excutable or all i need my main quake 3 arena excuteable?

You don't need any of the vanilla Q3 executables.

**Comment by DOOMMARINE117** [comment]
> 
> 
> > is there excutable or all i need my main quake 3 arena excuteable?
> 
> You don't need any of the vanilla Q3 executables.
> 
> > thsi supports bots an widescreen right?
> 
> Yes, although the widescreen support is the same as in the original game. You can adjust the FOV using `/cg_fov X` in the console, but the HUD will be stretched on non-4:3 aspect ratios.

all i do is extract the zip folder to the quake 3 arena installation folder right?

**Comment by Calinou** [comment]
@DOOMMARINE117 It's suggested that you take the `pak0`-`pak8.pk3` files from your Q3A installation's `baseq3` folder and copy them into a new `baseq3` folder that you place next to the ioquake3 executable instead.

**Comment by DOOMMARINE117** [comment]
> 
> 
> @DOOMMARINE117 It's suggested that you take the `pak0`-`pak8.pk3` files from your Q3A installation's `baseq3` folder and copy them into a new `baseq3` folder that you place next to the ioquake3 executable instead.

cool. 

where do i get the ioquake3 executable at?

**Comment by NuclearMonster** [comment]
Precompiled binaries are currently unavailable. Please discuss ioquake3 on https://discourse.ioquake.org/
