### ISSUE TITLE
Cannot close console with Czech keyboard

### ISSUE THREAD

**Issue by Rengaf05** [ioquake/ioq3#483]
Hello!
I love your code and I started making game from it. But the thing is that I cannot close console with key. I have to type toggleconsole to close it. When I press the console key it just types the semicolon (I have Czech keyboard). Dont misunderstand me I can open it with key. I tried binding it on F keys, numpad keys, normal keys (a to z) and even on ESC with no success. It just types the letter/symbol and doesnt do the bind (except for ESC, when Im in game it toggles the menu). Im using the latest code/commit. I just edited the Makefile and q_shared.h (I was working on the assets). I even tried to compile the plain code, but I have the same problem.

OS: Windows 10 Pro
Compiler: MinGW / Msys 1.0

**Comment by NuclearMonster** [comment]
Glad to hear about another game built with the source! Try the shift and escape keys at the same time to open or close the console if you haven't already, they're our built-in backup method.

**Comment by Rengaf05** [comment]
Thanks! That worked. Is there any way to patch this issue?

**Comment by KuehnhammerTobias** [comment]
Hello @Rengaf05!

This is a well known issue, there are also various issue tickets concerning this issue e.g: https://github.com/ioquake/ioq3/pull/285
Unfortunately this issue was never fixed in a good way.
Greetings to the Czech Republic!

**Comment by Rengaf05** [comment]
Ok! I will close it now
