### ISSUE TITLE
Feature Request:  Weapon  FOV

### ISSUE THREAD

**Issue by ConHuevosGuey** [ioquake/ioq3#484]
Would it be possible to implement a seperate FOV variable for the weapon FOV.  Yamagi Quake 2 does this, I'm no C++ expert, only a hobbyist but it's above my skill level.  

https://github.com/yquake2/yquake2/blob/b1ad1329ccd3ec03cf9568332f4f733c654cdd25/src/client/refresh/soft/sw_alias.c#L709

Here is (I think) the Quake 2 implementation.

**Comment by ensiform** [comment]
It's a mod related change, not essentially doable from ioquake3 on an engine standpoint.

Plenty of mods probably already have such features if they are actively developed.

**Comment by ConHuevosGuey** [comment]
I don't understand what you mean?  How is this not possible to do from an engine standpoint?  It's essentially an engine issue with drawing the weapon model.

**Comment by ensiform** [comment]
The weapon model and fov setup is rendered in cgame (cg_view.c) of the cgame.qvm how is that hard to understand?

**Comment by tomkidd** [comment]
This functionality is handled in a different place in Quake 3/id Tech 3 than it is in Quake 2/id Tech 2, either because id Software decided it needed to be a mod-friendlier location or because the yquake2 guys decided it needed to be in the engine renderer. 

yquake2 has overhauled and moved around several things in the Quake 2 engine, so it's possible that's why this is in their renderer as opposed to the client code.

**Comment by timangus** [comment]
> The weapon model and fov setup is rendered in cgame (cg_view.c) of the cgame.qvm how is that hard to understand?

How hard is it to be polite?

**Comment by ConHuevosGuey** [comment]
I see.  I will look for alternative solutions then.  Thanks.

**Comment by KuehnhammerTobias** [comment]
@ConHuevosGuey you can eventually play around with the cg_gunx, cg_guny, cg_gunz variables. Though, it doesn't really solve the problem,...

**Comment by themuffinator** [comment]
I have a source port based on q3e (still very similar to q3e) that corrects FOV, including for view weapons:
https://github.com/themuffinator/dm-engine

**Comment by NuclearMonster** [comment]
@themuffinator I wish you the best of luck with your project but please do not use this project's issue tracking to advertise your project.

**Comment by themuffinator** [comment]
@NuclearMonster: I provided a solution when none was given.
