### ISSUE TITLE
There seem to be some bugs on the NoGhost Mod

### ISSUE THREAD

**Issue by Locustv2** [ioquake/ioq3#493]
Hello,
I am running some NoGhost mod on quakejs server (http://www.quakejs.com/) where you can play in browser.

Noghost is a  serverside mod:

1.16 / 1.11 / demo : http://www.noghost.net/modfiles/1.16/NoGhost.zip
1.32: http://www.noghost.net/modfiles/1.32/NoGhost_beta.zip 

I am currently using the 1.32 version and it works fine. However there is an issue that when players connect to the game, their configuration is reset and they are renamed to UnnamedPlayer.

Is this something that can be fixed?

**Comment by NuclearMonster** [comment]
This sounds like an issue where the mod or quakejs include a default configuration, or quakejs loses the player configuration when you connect to a server and are forced to switch to that mod, but in either case we aren't quakejs or the mod developers and most likely can't resolve this issue unless it is reproduced with an ioquake3 client and ioquake3 server running that mod.

**Comment by NuclearMonster** [comment]
If this can't be reproduced with ioquake3 or ioquake3 server and id quake 3 client then we can't really test it, please feel free to test again and let us know!

**Comment by Locustv2** [comment]
I think it's an issue with the quakejs itself. Only baseq3 games seems to always get the player name. other mods rename everyone to unnamedplayer
