### ISSUE TITLE
How to play the game on ubuntu18.04?

### ISSUE THREAD

**Issue by WilliamWangPeng** [ioquake/ioq3#496]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114537323-a3a44500-9c84-11eb-812e-4740f31a763b.png)  

thank you  
best regards to you  
William

**Comment by NuclearMonster** [comment]
Check out the executables in the build directory after compiling the game, you can also use "make install" or use whatever packages ubuntu provides for ioquake3.

**Comment by WilliamWangPeng** [comment]
> Check out the executables in the build directory after compiling the game, you can also use "make install" or use whatever packages ubuntu provides for ioquake3.

Hi dear @NuclearMonster   
what is wrong here?  
![image](https://user-images.githubusercontent.com/51076736/114560911-b0826200-9c9f-11eb-9f49-c4b8702ed6ef.png)

**Comment by NuclearMonster** [comment]
@WilliamWangPeng The error message is exactly what it says. The git source code includes no game data (levels, sounds, graphic files, etc) and it can't run without them or a substitute.

**Comment by NuclearMonster** [comment]
If you have any further issues with running the game, please comment on our forums here: https://discourse.ioquake.org
