### ISSUE TITLE
Question about safety of the QVM and its JIT compiler

### ISSUE THREAD

**Issue by BlueNebulaDev** [ioquake/ioq3#499]
This is a question, not a bug. I apologize if this is not the right platform for this.

How do you ensure that the QVM (both the interpreted version and the JIT compiled code) doesn't access memory of the engine?

I tried to look up for this information on the internet, I read that it's safe, but couldn't an explanation.

**Comment by tomkidd** [comment]
Hi there,

Thank you for your interest, although as this isn't a bug the more appropriate place to post this would be the ioquake3 Discourse forum, so if you wouldn't mind please head over there to ask it or search to see if it's been asked before.

https://discourse.ioquake.org/

This has the additional benefit of being more visible for people who might have the same question in the future. 

Thanks

**Comment by BlueNebulaDev** [comment]
Apologies for asking it here. I wasn't aware of the discord, thank you for directing me there.
