### ISSUE TITLE
Team Arena unable to insert key

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [ioquake/ioq3#503]
I've tried to insert CD key for team Arena, but when i press a key nothing od showing on screen. I've tried pressing spacebar to fix this as this was recommended in older issue, but it's not working. Tried on windows and Linux (both 64 bit)

**Comment by ensiform** [comment]
Did you try backsplaces? It might be filled with spaces

**Comment by TheEpicNoobZilla** [comment]
Yes

**Comment by TheEpicNoobZilla** [comment]
Is was filled with space
