### ISSUE TITLE
how to disable certain weapons? 

### ISSUE THREAD

**Issue by DartPower** [ioquake/ioq3#507]
how can i disable certain weapons? 
e.g. all weapons, except BFG and Railgun
and on certain maps 

e.g.
disableweapon bfg q3dm17
disableweapon railgun q3tourney4

**Comment by zturtleman** [comment]
Set cvar using `set disable_(map entity name) 1`. For example, `set disable_weapon_shotgun 1`. To re-enable, use `unset disable_weapon_shotgun`. List of map entities is in [code/game/bg_misc.c](https://github.com/ioquake/ioq3/blob/main/code/game/bg_misc.c#L65).

**Comment by DartPower** [comment]
Thanks a lot!

Offtop:
P.S. Please enable "Discussions" in this repo on github for user questions :)

**Comment by NuclearMonster** [comment]
Our discussion forums are located at https://discourse.ioquake.org
