### ISSUE TITLE
Add support to quake 3 cinematic mod

### ISSUE THREAD

**Issue by luca2125** [ioquake/ioq3#512]
Hi,

I ask if is possible add the support for quake 3 cinamatic mod:

https://www.moddb.com/mods/cinematic-mod-8k-and-16k-resolution-textures

actually work only on quake3e.

Thanks !

**Comment by KuehnhammerTobias** [comment]
It would be nice to know why this mod won't work for you. Is there an error message?
This is an issue tracker, if there is an issue that prevents you from loading the mod, it should be fixed. 
What exactly is the issue you have with this mod?

**Comment by NuclearMonster** [comment]
The developer says this mod requires 24GB of VRAM which is entirely unrealistic (a 3080 has 10GB VRAM). If a patch is submitted to remove engine limits and coincidentally makes this mod work, that’s ok. Otherwise I’ll be OK without supporting it.

**Comment by luca2125** [comment]
What says the Developer is only partially true, I have nvidia GTX 1060 6 GB that is a mid-low level GPU card and the game work fine with Quake3e at 1080p. Probably the developer mean to play at 4K that for my opinion if not very important.

At the moment I have tested only Quake3e (that work) and spearmint that I get this result:

This this command like work:

quake3e.x64.exe +set fs_game cpmaV_CiNEmatic +set r_customHeight 1080 +set r_customWidth 1920 +set r_mode -1 +set com_hunkMegs 756

but if I run this not work:

spearmint_x86_64.exe +set fs_game cpmaV_CiNEmatic +set r_customHeight 1080 +set r_customWidth 1920 +set r_mode -1 +set com_hunkMegs 756

![error](https://user-images.githubusercontent.com/55355625/124710572-3f98c200-defd-11eb-9318-cc91f2361c34.png)

//
Spearmint 1.0.2 win_mingw64-x86_64 Nov 3 2019
SSE instruction set enabled
----- FS_Startup -----
Using 'baseq3' as default game as specified in C:\Users\MarcoPanza\Downloads\Quake 3 Arena\spearmint-gamelist.txt.
Current search path:
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\cpmaV_CiNEmatic
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\cpmaV_CiNEmatic
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\fonts
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\fonts

0 files in pk3 files

if I set 'CiNEmaticV11062' in this command line I get:

Spearmint 1.0.2 win_mingw64-x86_64 Nov 3 2019
SSE instruction set enabled
----- FS_Startup -----
Using 'baseq3' as default game as specified in C:\Users\MarcoPanza\Downloads\Quake 3 Arena\spearmint-gamelist.txt.
Current search path:
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\CiNEmaticV11062
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak999.pk3 (135 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak888.pk3 (74 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak777.pk3 (271 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak666.pk3 (56 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak555.pk3 (490 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak333.pk3 (440 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak222.pk3 (34 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\CiNEmaticV11062\zzzpak111.pk3 (20 files)
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\settings\fonts
C:\Users\MarcoPanza\Downloads\Quake 3 Arena\fonts

1520 files in pk3 files

with the some error message

//

**Comment by NuclearMonster** [comment]
The error message in that screenshot is most likely from spearmint not finding the Quake 3 Arena data in the baseq3 folder or directory.
