### ISSUE TITLE
Bug with blinking water shader in opengl2

### ISSUE THREAD

**Issue by insellium** [ioquake/ioq3#521]
[Video](https://youtu.be/m2gjAvhh5rk)
Map + shaders: https://cdn.discordapp.com/attachments/449535939690233857/852310388238450688/mjt_water_testmap2.pk3

**Comment by zturtleman** [comment]
The blinking on the water shader is fixed by https://github.com/ioquake/ioq3/commit/93abc60a5b79e4b8cc1ab985a03c272cdb0d0bb1.

**Comment by insellium** [comment]
finally
