### ISSUE TITLE
Running macOS x86 build fails

### ISSUE THREAD

**Issue by zturtleman** [ioquake/ioq3#527]
Trying to run the macOS x86 build (on x86_64 computer) fails because `/usr/local/lib/libSDL2-2.0.0.dylib` is missing. This is probably caused by the recent SDL update to 2.0.16.

```
./build/release-darwin-x86/ioquake3.x86
dyld: Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
  Referenced from: /Users/name/Desktop/ioq3/./build/release-darwin-x86/ioquake3.x86
  Reason: image not found
Trace/BPT trap
```

otool -L ioquake3.x86 lists `/usr/local/lib/libSDL2-2.0.0.dylib`.
otool -L ioquake3.x86_64 lists `@executable_path/libSDL2-2.0.0.dylib`.

This can be fixed by running `install_name_tool -id "@executable_path/libSDL2-2.0.0.dylib" code/libs/macosx/libSDL2-2.0.0.dylib`. I don't know if it needs to be code signed again.

Note: make doesn't automatically pick this up. If you have a mac x86 build, remove ioquake3.x86 and x86 renderers manually and run make to re-link the files to update SDL path. (The Makefile doesn't have client/renderers depend on the SDL dylib I guess.)

**Comment by futurepr0n** [comment]
any chance you can help - I am finding the same issue when building.
![Screen Shot 2022-06-13 at 9 19 53 PM](https://user-images.githubusercontent.com/478986/173473295-a1c30507-5a17-40fc-ab04-9c882daf0a6c.png)
![Screen Shot 2022-06-13 at 9 21 02 PM](https://user-images.githubusercontent.com/478986/173473401-2afe659e-7aa4-4324-aa80-89cd6d034745.png)

I am not sure exactly what to be doing.

**Comment by zturtleman** [comment]
That appears to be a different issue.
