### ISSUE TITLE
Screen not centered in M1 version using external monitor (widescreen)

### ISSUE THREAD

**Issue by diegoulloao** [ioquake/ioq3#532]
I just tried the M1 binary version for macbook and I get the screen out of center (fullscreen).

I downloaded the binary directly from the site. I'm using:
- macOs Monterrey 12.0.1
- external widescreen monitor LG 5120x1440
- m1 macbook pro 13-inch 2020

Intel version (rosetta) works fine.

**Comment by NuclearMonster** [comment]
You may need to manually configure the resolution for the secondary monitor using the commands in the player's guide: https://ioquake3.org/help/players-guide/#hd

**Comment by diegoulloao** [comment]
> You may need to manually configure the resolution for the secondary monitor using the commands in the player's guide: https://ioquake3.org/help/players-guide/#hd

I did it

**Comment by NuclearMonster** [comment]
Hmm, we don't have anything built-in to select a particular monitor as far as I recall.

**Comment by NuclearMonster** [comment]
For a discussion of the issue with the later please see #535
