### ISSUE TITLE
Linux and mobile platforms sections missing from the players guide

### ISSUE THREAD

**Issue by pmusset** [ioquake/ioq3#533]
There are links for the [linux](https://ioquake3.org/help/players-guide/#linux) and [mobile platforms](https://ioquake3.org/help/players-guide/#mobile) in the index but there is nothing where they should be (I suppose between [MacOS/Where are my files](https://ioquake3.org/help/players-guide/#macoswhere) and [Something isn’t working right!](https://ioquake3.org/help/players-guide/#somethingwrong))
I tried to acces the page on firefox on fedora and android, and on chromium on fedora so I don't think it's a browser problem

**Comment by NuclearMonster** [comment]
Fixed, but with the outdated content from the internet archive. Hope to get updates to this.
