### ISSUE TITLE
Some ground textures have bright patterns on Apple M1 computers

### ISSUE THREAD

**Issue by vashat** [ioquake/ioq3#537]
Seams there are texture glitches on the Apple M1 build. See enclosed screenshots. These do not appear through Intel version with Rosetta.

![Skärmavbild 2022-01-01 kl  14 02 35](https://user-images.githubusercontent.com/1157672/147851160-a5ac7b37-5d72-4b40-b9ce-f43aefac4411.png)
![Skärmavbild 2022-01-01 kl  14 02 13](https://user-images.githubusercontent.com/1157672/147851164-7cfd9cc8-7cb9-4b30-957f-f5d9e14d0363.png)

**Comment by NuclearMonster** [comment]
Reproduced this issue on q3dm3 with an M1 Mac, as in the screenshots

**Comment by NuclearMonster** [comment]
Good suggestion by Ensiform, the original (opengl1) renderer does not have this issue.

**Comment by KuehnhammerTobias** [comment]
@vashat probably this bug is related to cube mapping. Try setting r_cubeMapping to 1 (open the console and type \r_cubeMapping 1; vid_restart). 
Does changing the cubemapping cvar fix this issue?

**Comment by ec-** [comment]
It is not related only to M1 but to all ARMs because of slightly different (better?) FPU precision caused by scalar MLA (Multiply-Add) instructions

**Comment by vashat** [comment]
Unfortunatly, using setting r_cubeMapping to 1 did not help. When forcing the same binary to run in Rosetta on same machine, then textures are fine. Texturea are also fine when using opengl1 under native.

**Comment by Calinou** [comment]
As I said on IRC, we may want to consider using OpenGL 1 by default on macOS when using an ARM binary. It looks mostly similar to OpenGL 2 by default anyway.

**Comment by NuclearMonster** [comment]
> As I recently said on IRC, we may want to consider using OpenGL 1 by default on macOS when using an ARM binary. It looks mostly similar to OpenGL 2 by default, and it'll also perform better.

Performance and compatibility are high with the OpenGL 2 renderer. The default is not changing.

**Comment by zturtleman** [comment]
Fixed by ec- in https://github.com/ioquake/ioq3/commit/6d74896557d8c193a9f19bc6845a47e9d0f77db2.
