### ISSUE TITLE
Mac M1 (ARM64) ioquake3 ignoring console commands and ignoring/resetting q3config.cfg

### ISSUE THREAD

**Issue by eduardodesigner** [ioquake/ioq3#541]
Running in a Macbook Air 10,1 (M1 2020)
macOS Monterey 12.1

sv_cheats "1" in q3config.cfg is ignored and reset to "0"
cg_bobUp "0.000" in q3config.cfg is ignored and reset to "0.005"

Attempting to type those commands in the console yields no results (ioquake3 simply ignores them as if they didn't exist).
Attempting to put those commands in autoexec.cfg also yields no results.

**Comment by NuclearMonster** [comment]
I believe you have to use /devmap to load the map before cheats can be enabled
