### ISSUE TITLE
macOS Big Sur RX580 ioquake3 runs in "power save mode"

### ISSUE THREAD

**Issue by lyons88** [ioquake/ioq3#564]
IOQuake3 isn't triggering the higher clocks of my RX580 in macOS Big Sur( Intel ) The RX580 stays @300Mhz Core and Memory Clocks when running the game.

**Comment by lyons88** [comment]
In the time demo I'm getting about 335 FPS with s_initsound 0.

I have a utility( OpenGL Profiler ) to monitor the clock rates for the card while I run the demo or play the game and they never move from 300Mhz.

These clocks should be ramping up to the max( 1340Mhz Core/ 2000Mhz Memory when we call the OpneGL context( launch the game ).

**Comment by Calinou** [comment]
> These clocks should be ramping up to the max( 1340Mhz Core/ 2000Mhz Memory ) when we call the OpneGL context( launch the game ).

This only occurs if the game incurs significant enough load on the GPU. Lightweight GPU workloads intentionally don't cause clocks to raise to the maximum value to save power.

**Comment by NuclearMonster** [comment]
Looks like everything is working as best as it can to the GPU driver. 300+ FPS sounds great!

**Comment by lyons88** [comment]
Cranking up the graphics settings resolves the issue.
