### ISSUE TITLE
ioq3 1.36 downloads map in an endless loop

### ISSUE THREAD

**Issue by smx12** [ioquake/ioq3#567]
I have ioq3 1.36+u20191029.dc0c3e7 on Ubuntu 20.04 and when I try to connect to a server that has a map that I dont have it downloads the file and when it finishes downloading the file it starts to download it again in an endless loop. Why is this happening and how can I fix it?

**Comment by NuclearMonster** [comment]
Unfortunately this is most likely this is due to a misconfiguration of the server. Without knowing the specific server or circumstances we cannot guess.

**Comment by NuclearMonster** [comment]
Please feel free to reopen if you can provide more details

**Comment by smx12** [comment]
Hi, I discovered that I can open the quake 3 console by pressing "~" while its trying to connect, and the problem is that it disconnects from the server and then it reconnects that's why the endless loop. The server IP is 45.173.130.54:27967. Also there is a message on the console that says 'Unknown command "weapon"'. Any idea what it means?
