### ISSUE TITLE
ioquake disconnects from server and reconnects in a loop

### ISSUE THREAD

**Issue by smx12** [ioquake/ioq3#568]
While trying to connect to the following server 45.173.130.54:27967 I see in the console the following message: "'Unknown command "weapon"'. It then disconnects and tries to connect again. Any idea what that is and why? thanks!

**Comment by Chomenor** [comment]
I can't reproduce this particular problem connecting to the server. The server does seem to be poorly configured though, as it downloads files to baseq3 that could cause problems in other places.

A console log could be useful. If you run ```set logfile 2``` in the console before connecting to the server it should create one.

You could also try my filesystem update project for ioquake3 [here](https://github.com/Chomenor/ioq3_new_filesystem/releases). It might help with this kind of problem.

**Comment by Chomenor** [comment]
It looks like you might be running some sort of demo package of the game, not a standard ioquake3 install. If you don't have a full installation including a baseq3 directory and the pak0-pak8 pk3s, you probably won't be able to play on most online servers.

**Comment by smx12** [comment]
I've installed all pak*.pk3 files and now it works fine, thanks!!
