### ISSUE TITLE
Cant load opengl subsystem error

### ISSUE THREAD

**Issue by gregorypiro** [ioquake/ioq3#574]
Hi everyone. Greetings. I have this:

./baseq3/pak0.pk3 (3539 files)
    
----------------------
4128 files in pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
execing autoexec.cfg
Hunk_Clear: reset the hunk ok
----- Client Initialization -----
----- Initializing Renderer ----
Trying to load "renderer_opengl_x86_64.so" from "."...
Loading "renderer_opengl_x86_64.so" failed
failed:
"Failed loading ./renderer_opengl_x86_64.so: ./renderer_opengl_x86_64.so: cannot open shared object file: No such file or directory"
Trying to load "renderer_opengl2_x86_64.so" from "."...
-------------------------------
QKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
----- Client Shutdown (Client fatal crashed: GLimp_Init() - could not load OpenGL subsystem) -----
RE_Shutdown( 1 )
Hunk_Clear: reset the hunk ok
-----------------------
GLimp_Init() - could not load OpenGL subsystem
tty]

Anyone know what to do?

**Comment by NuclearMonster** [comment]
You have an incomplete installation of ioquake3 that is missing the files mentioned.

**Comment by gregorypiro** [comment]
@NuclearMonster you are right i ve done it one more time and it works but:

![Zrzut ekranu z 2022-09-12 01-37-00](https://user-images.githubusercontent.com/112812393/189554519-2a40a364-016d-4e19-828e-52c9786986ee.png)

![Zrzut ekranu z 2022-09-12 01-40-23](https://user-images.githubusercontent.com/112812393/189554527-1717ac65-c95e-4e51-8017-941c833c6ba2.png)

I attached the screenshots, as you can see my display is small, why is that?

**Comment by NuclearMonster** [comment]
have you tried setting a higher resolution? https://ioquake3.org/help/players-guide/

**Comment by gregorypiro** [comment]
I mean it is better now but still:

![Zrzut ekranu z 2022-09-12 02-07-24](https://user-images.githubusercontent.com/112812393/189554913-825674af-4e79-4811-a7ec-d8e496fec5c9.png)
Something like this :/

**Comment by NuclearMonster** [comment]
Press alt+enter to make the game full screen

**Comment by gregorypiro** [comment]
Great! @NuclearMonster thanks for help. Before i close the subject will you tell me if ioquake engine is better then others for example excessive mod plus?

**Comment by NuclearMonster** [comment]
I think ioquake3 is better but there are a few other notable forks, you should use whichever works best for you.
