### ISSUE TITLE
Mac (M1, Monterey) minor graphical glitches

### ISSUE THREAD

**Issue by ColinH** [ioquake/ioq3#582]
ioquake3 works really well on my M1 Mac mini (kudos to everybody involved, being able to play Q3A natively on a macOS 12 ARM64 Mac is just great) with one minor issue: There is a graphical glitch that might be related to curved surfaces. Attached are two screenshots that show the issue. Please let me know if there is anything else that I can do to help.

![Q31](https://user-images.githubusercontent.com/113184/206914258-1ff695ef-61f5-4a8d-a6f5-1ae26ba4c79e.jpg)
![Q32](https://user-images.githubusercontent.com/113184/206914260-471d7c3b-f1c4-41ed-8764-72c1f76bdc7e.jpg)

**Comment by Calinou** [comment]
This should be fixed in the latest daily builds: https://github.com/ioquake/ioq3/issues/537

**Comment by ColinH** [comment]
Thanks, then I'll wait until the official download contains this fix or I get around to compiling everything myself.

**Comment by ColinH** [comment]
Just checked out and compiled the main branch, it's fixed. Thanks again!
