### ISSUE TITLE
ioquake3.x86_64: Error SDL2.dll not found, it isn't using SL264.dll anymore

### ISSUE THREAD

**Issue by LegendaryGuard** [ioquake/ioq3#587]
The compilation builds _SDL264.dll_ for x64, then I copy the builds and when I run, that window error shows:
```
Code execution cannot continue because SLD2.dll was not found. This problem can be fixed by reinstalling the program.
```

If I rename the file to _SDL2.dll_, the program runs without errors.

**Comment by zturtleman** [comment]
Fixed SDL build in #573.

Duplicate of #528.
