### ISSUE TITLE
Cannot run the game on macbook m1

### ISSUE THREAD

**Issue by shalak** [ioquake/ioq3#589]
I'm running `Ventura 13.2.1 (22D68)`. After extracting `ioquake3_notarized.zip` file and moving the `ioquake3.app` to `Applications`, I copied the `pak0.pk3` file to `/Users/username/Library/Application Support/Quake3/baseq3/pak0.pk3`. The game doesn't start - it shows an error with:

> Point Release files are missing. Please re-install the 1.32 point release. Also check that your ioq3 executable is in the correct place and that every file in the "baseq3" directory is present and readable. See "/Users/username/Library/Application Support/Quake3/baseq3/crashlog.txt" for details.

`crashlog.txt` content:
```
tty console mode disabled
ioq3 1.36_GIT_96db7a06-2021-07-19 macosx-arm64 Sep 12 2021
----- FS_Startup -----
We are looking in the current search path:
/Users/username/Library/Application Support/Quake3/baseq3
/Users/username/Library/Application Support/Quake3/baseq3/pak0.pk3 (3539 files)
/Applications/ioquake3.app/Contents/MacOS/baseq3
/Applications/baseq3

----------------------
3539 files in pk3 files
Point Release files are missing. Please re-install the 1.32 point release. Also check that your ioq3 executable is in the correct place and that every file in the "baseq3" directory is present and readable
```

I tried following the [macosinstallation](https://ioquake3.org/help/players-guide/#macosinstallation), but the link to test builds (step 3) that is present there leads to an empty page.

What am I missing?

**Comment by tomkidd** [comment]
You need to install the point release files (basically the patches the game received between 1.0 and 1.32).

You can get them here:
https://ioquake3.org/extras/patch-data/

**Comment by NuclearMonster** [comment]
Thanks for reporting this issue, we're working on the website to make things clearer
