### ISSUE TITLE
MacOS mouse trigger lag

### ISSUE THREAD

**Issue by csotiriou** [ioquake/ioq3#599]
Hello, I am experiencing a fairly good bit of lag in the mouse trigger (left click) that I use for firing. I'm using a wireless Magic Mouse, but I have also tried other wireless mice with the same results.

- When I move the mouse, the response is instantaneous
- When I click the mouse to fire, there is a response delay of approx 300-500ms. The rest of the game works normally, and there is no hiccup during this time
- When I use the keyboard to fire, there is no delay, the response is instantaneous.

I'm trying to figure out what's going on, but I haven't got the slightest clue.

I'm using a 16-inch MBP Apple Silicon M1, with macOS Ventura 13.2. I'm using the latest version of the binary, and I have also compiled the latest version on the main branch. I'm getting constantly very high FPS (80-100), so I don't think that game performance is the culprit here...

**Comment by NuclearMonster** [comment]
Please update macOS to 13.4 and let us know if the delay is still there.

**Comment by csotiriou** [comment]
Thanks, I will try to do that later today. 

Just out of curiosity and pure software interest, is there anything in particular that we know Apple fixed (a mention in the release notes or something like that) that could positively affect this issue?

**Comment by Calinou** [comment]
This is likely trackpad palm rejection doing its thing, but with an external mouse.

Can you reproduce this in other games?

**Comment by csotiriou** [comment]
OK, so here's what I found:
- Upgrading to the latest macos version only slightly improved the issue.
- Using another wireless mouse with a wireless dongle did not improve the issue.

Here is a video with the issue:
https://www.youtube.com/watch?v=doSlSEYkIdg
- From 0-14 seconds, I am hitting the **mouse trigger** constantly
- From 14 seconds till the end, I am doing the same thing **with the keyboard** without using the mouse

You see the difference between the keyboard and the mouse, there is some kind of "lock" when hitting the mouse trigger, which only locks the player movement - it doesn't lock the rest of the game, and the frame rate is unaffected. 

To your question as to if it happens with other games:
Yes, it does in some of them! Probably the reason why I didn't notice it before is that Quake3 is much faster than other games, and lag is noticeable. There are other games that this doesn't happen, though, and I'm examining my library and trying to find why this happens. 

My next steps:
- Test ioquake3 with my intel iMac. 
- Find a **wired** mouse and see if there is any difference.

**Comment by csotiriou** [comment]
Well, the only thing that I haven't tried is a wired mouse, but I don't have any high hopes...
- My Intel mac behaves the same way with ioquake3
- vkquake (https://github.com/Novum/vkQuake) also has the same issue with ioquake3.
- Games like Dusk **don't** exhibit the same behaviour in any scenario - there is no problem with the input, either in Mac or in Windows, in any architecture. 
- Running ioquake3 in Parallels, windows 11 **doesn't** exhibit the same behaviour, the input is normal.

So the problem is found with Mac machines and only in specific titles, and I tend to believe that there is a specific library / configuration that is shared across all games that have the same issue (ioquake3 is one of them), which is why others are unaffected.

**Comment by csotiriou** [comment]
Hello again, I believe that I have found the issue. It seems that an application called **Magnet** is causing the issue. Why this is causing issues in some games and not others, I cannot understand. 

But when quitting it, there is no noticeable lag when playing.

Thank you for your answers!
