### ISSUE TITLE
Emscripten CD Key valid but still doesn't show levels

### ISSUE THREAD

**Issue by futurepr0n** [ioquake/ioq3#681]
I have my valid CD Key, and even after i input it and show valid, it will only show me the demo level

![Screenshot 2024-08-01 at 11 30 46 PM](https://github.com/user-attachments/assets/28c53852-6097-4316-8bef-b26b57b4f0c6)

![image](https://github.com/user-attachments/assets/fe8fcc4a-ef3d-47f1-812a-75da0c53a8c6)

Game appears fine, boots fine.
![Screenshot 2024-08-01 at 11 32 30 PM](https://github.com/user-attachments/assets/c4ca74d8-f1c8-44da-bee6-d7e06a0c239d)

**Comment by NuclearMonster** [comment]
Can you load other maps through the console? If you complete the first match do more show up?

**Comment by futurepr0n** [comment]
I will try that, thanks. I also wonder, is it possible to join other servers from a hosted emscripten client? I tried loading up two separate browsers and neither could find the server I started on browser1 that I had tried to start a server on. And neither browser seems able to find other games. Great stuff! I have compiled for mac, and emscripten now, but I just want to get more familiar on how it loads up and works because I want to be able to host a modified version of Q3 eventually with custom stuff I work on

**Comment by NuclearMonster** [comment]
At this time I don't believe the emscripten version has multiplayer.

**Comment by futurepr0n** [comment]
It does allow me to create an empty server with whichever level and then add bots, and also as you previously suggested, once i beat the demo I am able to be moved to the full game where it unlocks the tier I just completed. Thanks for your help
