### ISSUE TITLE
Suggestion: Add web page for getting the Quake 3 data files

### ISSUE THREAD

**Issue by zturtleman** [ioquake/ioq3#686]
The missing pk3 errors for baseq3 and missionpack now link the Quake 3 patch data https://ioquake3.org/extras/patch-data.  (Screenshots at #634.) The user is left to find how to buy Quake 3 on their own.

Suggestion: Create a page that links to buying Quake 3 (on Steam, GOG, MS store, ...) and links to downloading the patch data on ioquake3.org. Maybe call the page `https://ioquake3.org/quake3`.

This way the missing pk3 error can direct to a page with how to buy Quake 3 and/or download the patch data. This may be able to use affiliate links (like on [mac source ports](http://www.macsourceports.com/game/quake3arena)). It could potentially link to the [Quake 3 on sale thread](https://discourse.ioquake.org/t/quake-3-on-sale-thread/).

It could also note that Team Arena missionpack/pak3.pk3 is not included in stores and the patch data should be downloaded as well to get it.

**Comment by NuclearMonster** [comment]
I'll make a redirect to make it easier, like buy.ioquake3.org

**Comment by NuclearMonster** [comment]
Great suggestion, buy.ioquake3.org now redirects to the discourse thread, with a note there about the missing pk3.

**Comment by zturtleman** [comment]
Lovely, thank you. https://github.com/ioquake/ioq3/pull/692
