### ISSUE TITLE
Why do MAX_FLARES for opengl1 and opengl2 renderers differ?

### ISSUE THREAD

**Issue by kai-li-wop** [ioquake/ioq3#687]
Just stumbled about this and  wonder why do MAX_FLARES for opengl1 (256) and opengl2 (128) renderers differ? The limit for opengl1 renderer was changed back in 2013.

**Comment by zturtleman** [comment]
The OpenGL2 renderer was added to ioq3 after the MAX_FLARES patch was submitted at https://bugzilla.icculus.org/show_bug.cgi?id=5463 (committed in https://github.com/ioquake/ioq3/commit/20a77764dd7f62101f8a3750471dab300a840858). Applying it to the OpenGL2 renderer was probably forgotten.

OpenGL2 uses MAX_FLARES 256 now https://github.com/ioquake/ioq3/commit/00d60d05c4c59acde8d89de1d17a3212e2b8b6b8.
