### ISSUE TITLE
Crash when starting tier 2 first level with HD textures (Z_Malloc: failed on allocation)

### ISSUE THREAD

**Issue by ralph303** [ioquake/ioq3#699]
I played the first tier without problems and when loading the first level of tier 2 (Q3DM4) the game crashed (see log).
I tried two different pak3 with HD textures (z_realesrgan4xplus.pk3 and pak9hdworld.pk3), both behave the same.

Error Message:
Z_Malloc: failed on allocation of 31457320 bytes from the main zone. See "crashlog.txt" for details.

[crashlog.txt](https://github.com/user-attachments/files/17993637/crashlog.txt)

Version of ioquake is the latest available on https://ioquake3.org/ for MacOS.

**Comment by ralph303** [comment]
It seems that this can be solved by setting those parameters:
+set com_zoneMegs 128 +set com_hunkMegs 192

Is this possible to do using a config file in the MacOS version or will I have to build some custom shell start script?

**Comment by NuclearMonster** [comment]
Once these parameters are set, you should be good to go as long as you play the same mod you previously used (baseq3, world of padman, etc.) the local files are in ```/Users/YOURNAME/Library/Application Support/Quake3/``` on mac, was that where you were editing them?

**Comment by timangus** [comment]
As you have noticed, they have to be on the command line. From memory I think it's because their values are read before the config file is loaded.

**Comment by NuclearMonster** [comment]
to note, too, connecting to a game server online can switch the settings/mod/etc and lose settings. In any case, this is most likely a question as opposed to a bug with ioquake3. Please feel free to continue chatting on our forum, right here: https://discourse.ioquake.org we'll be glad to see you there and you can use github to login there if you like!
